### ISSUE TITLE
`Profunctor` instance for `StateT`

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1067]
@vmarquez pointed out to me that `StateT` forms a `Profunctor`

**Comment by kailuowang** [comment]
I gave it a try and failed, since `S` appears in both input and output, it looks to me that for `S` it has to be invariant (you need both `S => NewS` and `NewS => S`. 
@vikraman or @ceedubs mind give some further instruction? 
Here is my attempt
```Scala
def diMap[C, D](f: C => S)(g: A => D)(implicit F: Functor[F]): StateT[F, C, D] =
    new StateT(F.map(runF)(run => (c:C) => F.map(run(f(c)))(p => ((???) , g(p._2))) ))
````

I need a `C` in the place of `???` but in `p` I got only a `S`

**Comment by vmarquez** [comment]
Err, I think I pointed out *Indexed*StateT is one. ;-)

**Comment by kailuowang** [comment]
ah, makes sense. since cats doesn't have `IndexedStateT` shall we close this one?

**Comment by ceedubs** [comment]
Oops I hadn't thought that through very well :)

Sorry for the false alert. Thanks for giving it a try @kailuowang and thanks for your input, @vmarquez.
