### ISSUE TITLE
Applicative/Functor instance missing for OptionT

### ISSUE THREAD

**Issue by tbrown1979** [typelevel/cats#1107]
Missing for when F doesn't have a Monad

**Comment by yilinwei** [comment]
This is absolutely the case because a monad transfromer is not the same as a `Nested`. 

See explanation here #1106.

**Comment by peterneyens** [comment]
It would still be possible to add something like `scalaz.OptionT[F, ?].app`, but it would give the same result as `Nested[F, Option, ?].ap` so that wouldn't be that useful probably.

I was wondering if we should add some sort of `toNested` on  `OptionT` and `XorT`, in that way you could do `OptionT(List(Some(1))).toNested.ap( ... )`.
We could probably also use it to implement methods like `OptionT.foldLeft` for `Foldable[OptionT[F, ?]]` (which I just added in #1103, which also includes the `Functor` you mentioned)

```scala
def foldLeft[B](b: B)(f: (B, A) => B)(implicit F: Foldable[F]): B =
  toNested.foldLeft(value, b)(f)
  // F.foldLeft(value, b)((b, o) => optionInstance.foldLeft(o, b)(f))
```

**Comment by ceedubs** [comment]
@peterneyens I like your idea of `toNested`.

**Comment by ceedubs** [comment]
`toNested` was added in #1172, so I'm going to close this out.
