### ISSUE TITLE
Profunctor instances for Function1

### ISSUE THREAD

**Issue by tel** [typelevel/cats#1176]
These should be natural:

```scala
// (Copied from a project of mine)
object Orphans {

  implicit object functionIsProfunctor extends functionIsProfunctor
  trait functionIsProfunctor extends Profunctor[Function1] {
    def dimap[A, B, C, D](fab: A => B)(f: C => A)(g: B => D) =
      f andThen fab andThen g
  }

  implicit object functionIsStrong extends functionIsStrong
  trait functionIsStrong extends functionIsProfunctor with Strong[Function1] {
    def first[A, B, C](fa: A => B) = { case (s, c) => (fa(s), c) }
    def second[A, B, C](fa: A => B) = { case (c, s) => (c, fa(s)) }
  }

  implicit object functionIsChoice extends functionIsChoice
  trait functionIsChoice extends functionIsProfunctor with Choice[Function1] {
    def left[A, B, C](p: A => B) = _.bimap(p, identity)
    def right[A, B, C](p: A => B) = _.bimap(identity, p)
  }

}
```

If `Tuple` had bimap then the definitions would be parallel, interestingly enough.

**Comment by ceedubs** [comment]
Since `Arrow` extends both `Profunctor` and `Choice`, I think all of these should be provided by [this instance](http://typelevel.org/cats/api/index.html#cats.std.FunctionInstances@function1Instance:cats.arrow.Choice[Function1]withcats.arrow.Arrow[Function1]). @tel please let me know if I'm missing something or if there is a way we could make this better documented or otherwise clearer.

**Comment by tel** [comment]
Hm, that seems correct. Maybe I was misusing something in that I got implicit resolution problems. I'll take another look.
