### ISSUE TITLE
Reconsider overloading in NonEmptyVector

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1204]
Currently [NonEmptyVector](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/NonEmptyVector.scala) has overloaded `concat` and `++` methods supporting both `NonEmptyVector` and `Vector` as the arguments.

In general I'm a bit skeptical about overloading. In this specific case the main downside I see is that it prevents us from turning `NonEmptyVector` into a value class (which seems like it might be an otherwise reasonable thing to do).

What do people think?

**Comment by mikejcurry** [comment]
:+1: on removing the overloading as a general principle. Also, having a value class would be useful in specific use cases. 

The syntax is still useful for working with Vectors directly though. Maybe a rename to `concatVector` or `appendVector` and a different operator such as `+++`.

As an aside, with regard to value classes, it is worth bearing in mind that, as I understand at least, invoking any general code that involves summoning an instance would negate the benefit of the value class. i.e. summoning the `Semigroup` for `NonEmptyVector` would require an instance of `NonEmptyVector` to be instantiated - because `NonEmptyVector` would be being used as a type argument to `Semigroup` and one of the limitations on value classes is that if they are used as type argument an instance needs to be instantiated. I think having `NonEmptyVector` as a value classes is still useful despite this, because it opens up options to users of the class.

**Comment by mikejcurry** [comment]
Believe this should be resolved by #1212
