### ISSUE TITLE
`Reader` is not an instance of `MonadReader`?

### ISSUE THREAD

**Issue by rongcuid** [typelevel/cats#1235]
Not sure if cats try to make use of MTL-like programming idiom. Currently when trying the `Reader` monad I found that it is not an instance of `MonadReader`, which means `ask`, `local` cannot be used. However, I notice that `State` has its `get`, `put`, etc. So can I guess that `Reader` has the functions unimplemented?

**Comment by adelbertc** [comment]
`Kleisli` should have it: https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/Kleisli.scala#L114

and `Reader` is just `Kleisli[Id, _, _]`. Maybe a SI-2712 issue? Try annotating types

**Comment by carldong** [comment]
Then what am I supposed to use in a `for` comprehension?

Currently I have to

```
env: Type <- Reader(identity[Type])
```

Is the correct way like this?

```
env <- Kleisli.ask
```

**Comment by adelbertc** [comment]
So `Kleisli` has an `ask` method directly on the companion object, so you can do something like `env <- Kleisli.ask[Option, Int]`. If you want to use `MonadReader` you should be able to get the instance via `MonadReader[Kleisli[Option, Int, ?], Int]` (if you have kind-projector)

**Comment by carldong** [comment]
Then what am I supposed to use in a `for` comprehension?

Currently I have to

```
env: Type <- Reader(identity[Type])
```

Is the correct way like this?

```
env <- Kleisli.ask
```

**Comment by ceedubs** [comment]
@carldong here is a small example of using `MonadReader` with `Reader`:

```scala
scala> import cats._, cats.data._, cats.implicits._
import cats._
import cats.data._
import cats.implicits._

scala> type R[A] = Reader[String, A]
defined type alias R

scala> val r = MonadReader[R, String]
r: cats.MonadReader[R,String] = cats.data.KleisliInstances4$$anon$3@7de44f6f

scala> import r._
import r._

scala> val f = for {
     |   s <- ask
     |   a <- pure(3)
     | } yield (s + "bar", a + 1)
f: cats.data.Kleisli[cats.Id,String,(String, Int)] = Kleisli(<function1>)

scala> f("foo")
res0: cats.Id[(String, Int)] = (foobar,4)
```

I think it'd be great if we could add some documentation for this sort of thing. Currently there is some [documentation on `Kleisli`](http://typelevel.org/cats/tut/kleisli.html), but it doesn't really go into anything like this.

**Comment by carldong** [comment]
Huh, I thought `import cats.implicits._` should do it. Should ther be something like `implicit val readerM[E] = MonadReader[R, E]` defined? Or am I understanding Scala implicits incorrectly(because I came from Haskell and there these things just work)

**Comment by ceedubs** [comment]
@carldong you are correct that `import cats.implicits._` _does_ bring in all of the type class instances that you need (via implicits). _However_, the MTL style is just kind of awkward in Scala (or at least the way that Cats has encoded type classes/MTL). In theory you could just `import Klielsi._` and that would bring its `ask`, `pure`, and `local` methods into scope and you could do exactly what I did above. In practice, type inference breaks down. So what we tend to do instead is to grab the actual instance of the `MonadReader` type class for the specific types that you are using (in my example `F` is `Id` and the input type is `String`) and use the methods on it instead, since the types are already fixed so inference isn't really an issue.

Just to be a bit more explicit about what was going on in my previous example, this is what it would have looked like if I hadn't used `import r._`. This may clear up what's going on there.

```scala
scala> import cats._, cats.data._, cats.implicits._
import cats._
import cats.data._
import cats.implicits._

scala> type R[A] = Reader[String, A]
defined type alias R

scala> val r = MonadReader[R, String]
r: cats.MonadReader[R,String] = cats.data.KleisliInstances4$$anon$3@7de44f6f

scala> val f = for {
     |   s <- r.ask
     |   a <- r.pure(3)
     | } yield (s + "bar", a + 1)
f: cats.data.Kleisli[cats.Id,String,(String, Int)] = Kleisli(<function1>)

scala> f("foo")
res0: cats.Id[(String, Int)] = (foobar,4)
```

So essentially we are (ab)using the fact that type class instances are actual objects that are being passed around in Scala so that we can lock in on the specific instance that has the types fixed to what we want to get around type inference issues.

I always feel a little silly and apologetic when I explain these sort of things to someone who is coming from Haskell where there is a much better MTL story :\

**Comment by carldong** [comment]
OK... Kind of hard to get used to a quite-functional-but-totally-not-pure language... I'll try to understand the implicits and type inference magics(for me).

Plus I'd check Fredge too.

**Comment by LukaJCB** [comment]
Can probably closed now :)
