### ISSUE TITLE
Possible to add MonadError[Option, A]?

### ISSUE THREAD

**Issue by andyscott** [typelevel/cats#1237]
There's already an instance of `MonadError[Option, Nothing]`. Would it be possible to add `MonadError[Option, A]` implicit instances?

```scala
implicit def catsStdMonadErrorForOption[A]: MonadError[Option, A] =
    new MonadError[Option, A] {
      def pure[B](x: B): Option[B] = Some(x)
      def handleErrorWith[B](fb: Option[B])(f: A ⇒ Option[B]): Option[B] = fb orElse None
      def raiseError[B](e: A): Option[B] = None
      def flatMap[B, C](fb: Option[B])(f: B ⇒ Option[C]): Option[C] = fb flatMap f
    }
```

I could see there being some issues with `handleErrorWith`. Not sure.

**Comment by johnynek** [comment]
is there a law that:

``` handleErrorWith(raiseError[A](a))(pure(_)) == pure(a)```

I would think we would want something like that, and the above violates it.

PS: `x.orElse(None) == x`

**Comment by ceedubs** [comment]
@andyscott what's the value in being able to pass in an `A` value if it's always ignored?

I think that this would violate at least one of the laws in `ApplicativeErrorLaws`/`MonadErrorLaws`, but I haven't taken a close look yet.

**Comment by andyscott** [comment]
I'd like to be able to do the following abstraction:

```scala
object Test {
  def doFoo[F[_]: λ[α[_] ⇒ MonadError[α, Throwable]]](value: Int): F[Int] =
    if (value > 100) MonadError[F, Throwable].pure(value)
    else MonadError[F, Throwable].raiseError(new Exception("value was less than 100"))

  val xorFoo = doFoo[Xor[Throwable, ?]](99)
  val optionFoo = doFoo[Option](99)
}
```

Currently this yields `could not find implicit value for evidence parameter of type cats.MonadError[Option,Throwable]`

**Comment by andyscott** [comment]
I've played around with this a bit and it definitely breaks the existing laws for `MonadError` (and `ApplicativeError`). Regardless, I'd like some way to perform the abstraction in my previous comment. Any ideas?

**Comment by ceedubs** [comment]
@andyscott `ApplicativeError` is an abstraction representing both the ability to raise errors _and_ to recover from them. In your case it seems like you can't recover from them, because in certain cases you are throwing the errors away.

You may want to create your own type class that extends `Applicative` and adds `raiseError` but not `handleErrorWith`. However, such a class wouldn't have very strong (if any) laws, and I'm not sure how generally useful it is. Therefore I think it's probably not something that belongs in Cats, so I'm going to go ahead and close this issue out. But feel free to continue the discussion in the Gitter channel.
