### ISSUE TITLE
Attribution or original author clause as part of contributor agreement

### ISSUE THREAD

**Issue by jdegoes** [typelevel/cats#1275]
See [here](https://twitter.com/puffnfresh/status/762790754066440192) for context.

Quick thoughts:

1. I'd suggest the CLA (which the project does not appear to have yet) mandate original authorship or proper attribution. Once such a policy is instantiated, every contributor could be contacted to certify original authorship or provide proper attribution, thus catching contributions up to the policy change.
2. I'd also suggest amending the COC to explicitly forbid copy/paste without compatible license and proper attribution — mainly so people know that intentional or uncorrected failure to comply is grounds for ejection from the community.

**Comment by travisbrown** [comment]
👎 to a CLA, 👍 to more explicitly forbidding copy-paste without proper attribution.

**Comment by johnynek** [comment]
+1 to this. It is fine to share code, but copyright and license annotations should be preserved.

I don't know the exact solution here because I am not familiar with what fraction of the code is copy/paste or trivial modifications of existing code.

One solution Brian mentioned was: https://twitter.com/puffnfresh/status/762811494719291393 but I don't think that's such a great solution as:
1. many on that list may not want to be added to contributors.
2. many may not in fact be contributors.

It seems Brian wants to be added or acknowledged in some way, so the first thing we could do is try to make a quick pass for the obvious candidates of places where the ball was dropped in the past.

**Comment by jdegoes** [comment]
For some, "contributors" may imply endorsement and / or intentional activity, so "Attribution" or some other section distinct from contributors and prefaced appropriately may be a more broadly appreciated way of providing attribution.

**Comment by johnynek** [comment]
So, this file is here (as pointed out in gitter):
https://github.com/typelevel/cats/blob/master/COPYING

which contains the scalaz notice.

That may not be enough. I still think if you contribute something you should state where it came from if not original work (whatever that means in this area that is so highly derivative of other work generally).

**Comment by jdegoes** [comment]
> That may not be enough. 

Indeed, the wording makes it seem like this was a one time thing that stopped in 2014 (based on the copyright). Not that it is being "continuously derived" from Scalaz, including recent 2016 code, and including many contributors not mentioned in the copyright notice, such as Brian McKenna.

> I still think if you contribute something you should state where it came from if not original work 

👍 In many projects, I often see these notices in the code itself, e.g. `This function was based on so and so's work ...` with proper attribution. That works.

Having had my open source work copied and not attributed before, I can attest it's not a particularly good feeling... in my case it was rectified soon after it happened, and there are no hard feelings. Not everyone is so lucky.

**Comment by stew** [comment]
@jdegoes note that when you say "the wording makes it seem like this was a one time thing that stopped in 2014", that we MUST not change this wording. It is exactly what is required by the scalaz redistribution license, see here:

https://github.com/scalaz/scalaz/blob/series/7.3.x/etc/LICENCE#L7-L8

If this copyright notice is to change, it should only change after scalaz changes their license.  We cannot add  Brian to this copyright notice without scalaz doing that first.

This is, of course, not to say that we cannot make some additional attribution to people that have contributed.

**Comment by fommil** [comment]
A CLA is a good thing but only if it agrees word for word with the License that is offered to the public. Don't do what Lightbend do and accept Apache code, but release under the weaker modified BSD.

This isn't a CoC concern. It's a legal and licencing concern. Let's not mix it up.

Attribution is a legal requirement if the original code has a copyright notice and a modified bsd style license (as do many other libre licenses). However, attribution is **not** a legal issue if the original code does not require it. Cats includes some scala code, and its license reflects this. I believe this "permissive use" is one of the many reasons why people choose these licenses, isn't it?

I'd like to point out that when you use bsd style license you should be aware of what rights you give up. I encouragee everybody to prefer Apache 2.0 over mit/bsd and better yet a copyleft license http://fommil.github.io/scalasphere16

**Comment by aloiscochard** [comment]
There is legal framework, for which you might give a shit but I don't. Then there is moral and netiquette.

For the later I think you should clearly attribute copy/pasted works, I think it's a shame it was not done properly before.

**Comment by fommil** [comment]
The scalaz license is here https://github.com/scalaz/scalaz/tree/series/7.3.x/etc but there is no license for 8.x and until there is, I recommend not deriving any works from it.

They could change to a license that is not compatible with cats. You cannot assume that the previous license applies.
Indeed, they are breaking their own license terms and a disgruntled contributor could kick up a fuss about it if they wanted.

As to this ticket, I vote to close. Cats is obliging the terms of the scalaz license and this ticket has been raised by proxy. If there was concern from a copyright owner that their license is not being respected, only they can bring it up. In this case, the copyright owner has said they don't want to update the scalaz license, which means they forfeit their right to attribution in derivative works.

**Comment by jdegoes** [comment]
> This is, of course, not to say that we cannot make some additional attribution to people that have contributed.

Exactly. IMO a copyright license is not the rug to sweep all attributions under. 

> A CLA is a good thing but only if it agrees word for word with the License that is offered to the public. Don't do what Lightbend do and accept Apache code, but release under the weaker modified BSD.

Note that a CLA provides other features important for some businesses, such as offering legal protection against submitting non-original work for which the submitter does not have sufficient rights; protection against use of patented materials or trademarks, etc. Some companies will not allow use of open source projects without a CLA.

At minimum, a CLA should allow the organization or project to issue the contribution under the project's same license (as you say above). One can argue this is implied by the Github model of development, but that has never been tested in any court, and I've seen some projects act as if this were not true.

> This isn't a CoC concern. It's a legal and licencing concern. Let's not mix it up.

The COC dictates terms by which you are allowed to participate in the community. Not giving a fellow developer explicit credit for her work is something that could conceivably fit into a COC (of course, it doesn't have to, and the consensus here seems to be that people don't want it to).

> However, attribution is not a legal issue if the original code 

This is not a legal issue, this is an issue of helping authors feel appreciated for their works by giving clear attribution. It's a professional tip of the hat in recognition of the hard work that others have done which makes projects like Cats possible.

> They could change to a license that is not compatible with cats. You cannot assume that the previous license applies. Indeed, they are breaking their own license terms and a disgruntled contributor could kick up a fuss about it if they wanted.

This seems useful advice. I think such guidelines (as well as any attribution requirements, of which there are none right now) may fit well in the contributor's guide, since I fear your above comment will be lost on this ticket and few who make future contributions will see it.

> As to this ticket, I vote to close.

I empathize with how Brian feels since I've been in a similar situation myself. I didn't mean to imply that Cats was breaking the law, I just wanted to propose a low cost way of tipping the hat to fellow developers. I'm not sure I understand why there is resistance against this idea, but in any case, I said what I wanted to and everyone heard me out, so thanks for your time.

**Comment by fommil** [comment]
@jdegoes 

> offering legal protection against submitting non-original work for which the submitter does not have sufficient rights

a CLA can't possibly protect against this, unless it requires the submitter to take the liability, which would be unlimited. All a CLA can realistically do is remind the contributor that they should only be submitting original content or flagging up derivatives work.

> At minimum, a CLA should allow the organization or project to issue the contribution under the project's same license 

Agreed. I consider such minimal CLAs to be good CLAs. Although I may add a gentle reminder about non-original works to all my CLAs.

> This is not a legal issue

Well it is and it isn't. Licenses formalise this sort of thing. If somebody wants to use a different mechanism to get attribution then really it just means they used the wrong license or don't understand why licenses exist.

**The same goes for any cats AUTHOR**... if you want attribution, be sure to update the LICENSE (or COPYING) file. There is absolutely no obligation on distributors of cats to include the AUTHORS file with source or binary distributions.

In ENSIME, we explicitly link to the git log from the LICENSE but we'd like to automate adding this information into the source files, see https://github.com/sbt/sbt-header/issues/35

**Comment by adelbertc** [comment]
Legalities aside, I think it is important as a matter of good form that original authors are credited where credit is due. To that end I think https://github.com/typelevel/cats/issues/1276 is a fair start. I hope moving forward Cats continues to credit original authors, be it from papers, Haskell, OCaml, Scala, any other language, and folks who've translated it from another language.

In the interest of moving forward, I hope some folks (perhaps @aloiscochard ?) can do us the favor of looking at https://github.com/typelevel/cats/pull/1276 and adding comments and/or suggestions to help resolve this.

**Comment by djspiewak** [comment]
Something which hasn't been mentioned here…  (disclaimer: I'm not a lawyer, just a legal hobbyist who's been around the OSS community for while)

US copyright law dictates that, in the event of a legal challenge on a copywritten work, at least 51% of all rightsholders must be notified and named.  This figure is not based on "lines of code" or anything intuitively obvious like that, but actually based on the complete unweighted list of rightsholders.  There are serious penalties if this constraint cannot be followed in the event of a challenge.

For projects with a lot of contributers (where "lot" is defined as "more than 2"), this is a huge, *massive* problem.  Like, insanely massive.  Tracking everyone down and getting confirmation that they have been notified within the time window (which is not long) is hard enough, but then getting them to participate in the legal action (which they are compelled to do) is even harder.  Mozilla ran into this several years ago, and it literally took them almost 2 years to get it all sorted out.  They're obviously an outlier case, but still.

Commercial companies and consultants (engaged in "work for hire", which has a rigid legal definition under copyright law) get around this problem entirely by attributing rights to the commercial entity who is also responsible for paying the creators.  This is why the "works for hire" clause exists in the first place.  I work for Verizon.  Verizon doesn't need me to sign a CLA to ensure that legal challenges on their code can be handled by them and them alone, since they're literally giving me money for the code that I produce for them.  Under this framework, I'm no longer a rightsholder (despite the fact that I created the work originally), and so I don't need to be involved in legal action.

If money *isn't* changing hands though, which is to say in nearly all open source work, this clause does not apply.  Even if there is a single legal entity which governs a project, if that entity is not paying contributors, then it doesn't qualify as "works for hire" and the contributors are still the rightsholders.

CLAs solve this problem.  The most important clause in a CLA is the grant of license (clause 2 in the [Apache CLA](https://www.apache.org/licenses/icla.txt)).  Without this clause, a CLA is meaningless and we're back in the "everyone needs to be individually involved in every legal action".  This is why Mozilla's solution to their massive legal contribution knot was to get everyone to sign a retroactive license grant, and then move to a CLA format for all future contributions.

CLAs also legally indemnify the organization from contributions of invalid provenance.  If you have a contributor has signed a CLA who copies someone else's code and claims it as their own work, the CLA is a legal failsafe in the event that said code is challenged by the original rightsholder.  The entity in charge of the project is no longer liable, because the contributor was the one who perjured themselves and violated the agreement, while the entity acted in good faith.  This is also *vitally* important for any non-trivial codebase.

Note that CLAs don't have to be a massive pain, though this is where we enter slightly more legally uncharted waters.  Gateway was involved in a US Supreme Court case back in the 90s which established the doctrine of a "shrink wrap agreement".  This acts as the legal precedent for projects who literally just drop their CLA into a `CONTRIBUTORS.md` file, with pointers from the `README.md` file, and call it a day.  This isn't the safest course of action, since this style of CLA verification hasn't actually been tested in court, but it does have some merit.  At the very least, it prevents a ton of overhead.

Here's the bottom line: **if you share source code, you need to care about CLAs.*  Full stop.  You can't just ignore this issue.  Either you, or Typelevel, or some company using typelevel's work is going to get in trouble eventually, and the legal fallout will be staggering without this kind of framework in place.  CLAs may suck, but they exist for a reason, and that reason is far broader than just "don't copy someone else's code".

Cats uses the MIT license, which does not have a pre-baked CLA anywhere (that I'm aware of).  Also, the MIT license has somewhat legally dubious protections in the event of patent claims and the like, but that's a larger discussion.  If typelevel means to stick with the MIT license, then they need to get a CLA written up which applies to it.  Another option would be to pivot to the Apache 2 license, which has a ready-made CLA, significant legal analysis, and appropriate patent protections.  Again, this is a longer discussion that seems out of scope here.

But at the end of the day, you *cannot* just ignore the CLA issue.  Not if you want to share and collaborate on source code in the US and/or with US developers.  (not ruling out similar EU or other problems; I'm just only familiar with US IP law)

**Comment by travisbrown** [comment]
> But at the end of the day, you cannot just ignore the CLA issue.

Well, maybe you _cannot_, but 99% of the open source projects I've ever contributed to _do_, and many of them have organizations with big legal departments as adopters, sponsors, and contributors.

I'm also not a lawyer, and to be honest I don't care about this legal stuff half as much as I probably should, but potential contributors _will_ bounce off a CLA that requires more participation than being directed to read a CONTRIBUTING file.

**Comment by djspiewak** [comment]
> Well, maybe you cannot, but 99% of the open source projects I've ever contributed to do, and many of them have organizations with big legal departments as adopters, sponsors, and contributors.

You don't have to take my word for it.  Look up anything related to the contributor process at Eclipse, Apache, Mozilla, or the other big organizations.  Look up *why* it is the way it is.  If I recall, Ian at the Eclipse Foundation actually has an essay about this somewhere.

Ignore it the issue if you like.  But I want you (well, really typelevel) to be absolutely clear on *exactly* the risk you're accepting by doing so.  It's your decision, not mine.

> I'm also not a lawyer, and to be honest I don't care about this legal stuff half as much as I probably should, but potential contributors will bounce off a CLA that requires more participation than being directed to read a CONTRIBUTING file.

So put the legal catch in the contributing file.  If you read my reply, you'll notice that I mention that alternative and also how it is that it can be legally justified (also the potential perils of it).

There's a reason CLAs exist.  A *very* good reason.  Ignoring that reason isn't "lean" or "low friction", it's simply risky.  If you think the risk is low enough to justify ignoring it, then fine, as I said that's your decision.  But the risk is objective reality, and there's no point in denying it.

**Comment by milessabin** [comment]
@djspiewak a lot of what you say makes sense in the context of US IP law. However things are very different elsewhere ... for instance, in Germany copyright assignment is impossible, even for work done for hire.

All Typelevel projects are international, Cats included, and it's important not to get bogged down in parochial concerns. I'd happily defer to @fommil, but my understanding is that Apache 2.0, without an additional CLA, is pretty close to optimal for free software (but not copyleft) projects across multiple jurisdictions.

**Comment by djspiewak** [comment]
@milessabin I agree fully.  In as it is important to ensure that typelevel projects are keeping their ducks in a row with respect to US IP law, other countries are just as important.  I certainly didn't mean to marginalize IP law elsewhere, I simply have no knowledge whatsoever on the subject outside of the US.

Apache 2.0 is a very safe bet.  I don't know anything more definitive about it than "yep, it's a safe bet", but there you go.  I will say that an additional CLA is unnecessary with Apache 2.0, since you get the CLA for free as part of the license.  Mentioning the CLA somewhere in the CONTRIBUTING document and adding license headers is probably sufficient, and doesn't impose any added friction on contributors.

**Comment by fommil** [comment]
If I'm being deferred to :-P I'll say that Apache 2.0 with a CLA that basically **is** the Apache 2.0 is about as good as you can get if you want to go the permissive licensing route. ENSIME uses https://cla-assistant.io/ highly recommended. A typical ENSIME CLA looks like https://gist.github.com/fommil/211088434c6187218ffa

**Comment by djspiewak** [comment]
Here's a random example of a "shrink wrap CLA": https://github.com/RichRelevance/scalaz-netty#license (also with apache 2.0).

**Comment by fommil** [comment]
@djspiewak there are also PR templates in github now. A cheap alternative to a CLA checker would be a template that just says "I agree to contribute this code under the terms of X"

**Comment by mbrcknl** [comment]
@fommil:
> In this case, the copyright owner has said they don't want to update the scalaz license, which means they forfeit their right to attribution in derivative works.

Whoa! I think you might have missed some steps in the legal argument there. (Since you're making legal arguments).

One question that has not been asked: If @puffnfresh is not represented in the scalaz license, do you have the rights to use his scalaz contributions *at all*?

IANAL, so I have no idea.

**Comment by fommil** [comment]
@mbrcknl no steps missed. That's the way it works. I really wish developers would care about these things and understand the licenses that they use. As copyright owner you are entitled to be *recognised* as the author, which could be verbal, or a letter, but there is no obligation for distributions or derivative works (source or binary) to list your name anywhere. This is exactly why the BSD licences are used, to require it.

If the copyright owner really wanted to push the limits of their legal power they *could* claim that they never agreed to the original license in the first place, in which case I refer you to Daniel's post regarding shrink wrapping (and also scalaz and their distributors/users would be in trouble). Like he says, there is a reason why the big organisations insist on copyright assignment or exclusive licensing agreements.

**Comment by mbrcknl** [comment]
@fommil

> I really wish developers would care about these things and understand the licenses that they use.

My question concerns *whether @puffnfresh applied the license to his scalaz contributions*. No-one other than @puffnfresh can do that, not scalaz, not you.

At a glance, I see no explicit shrink-wrap CLA in the scalaz code, so I'm not sure how that's relevant. I'm glad you're confident that it is implied. Given this issue and the surrounding conversation, I probably would not be.

I'm happy to forward you my IP lawyer's details, if you'd like her input. Last I checked, her rates were around AUD 500 per hour.

**Comment by fommil** [comment]
@mbrcknl it sounds like an issue you need to take up with scalaz, Brian and your lawyer if it concerns you. Everybody here seems to be happy with the implied license from the github workflow. I don't recall asking for your lawyer's details, perhaps you misunderstand: this is for your own peace of mind.

**Comment by jonoabroad** [comment]
I'd like to agree with the moral comment and point out unattributed code is plagiarism.

**Comment by jonoabroad** [comment]
Hi, I'd like to update my comment. I think my understanding of plagiarism is outdated, I was working on the defn of "the practice of taking someone else's work or ideas and passing them off as one's own." I should have said "I would like to see author attribution", I wasn't meaning to imply there _was_  plagiarism. Also this and the original comment was on the general movement of code and not this specific commit.

**Comment by fommil** [comment]
@jonoabroad it's definitely a good and moral thing to do to attribute code. If this is something people feel strongly about, then they should use a more appropriate license to force attribution rather than rely on friendly parties doing The Right Thing. In this case, adding one's name to the BSD LICENSE file achieves that.

**Comment by aloiscochard** [comment]
@fommil just so you know, some people can feel strongly about something without wanting to enforce it on others. For example maybe they tolerate it, even though it's not what they see as optimal.

Thanks for sharing your advice anyway.
