### ISSUE TITLE
only use squash commits

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats#1328]
https://github.com/blog/2141-squash-your-commits

Github supports only allowing squash commits to master. I think we should consider it. The issue with the Either partial revert recently would have been somewhat easier if we didn't have such a complex branch graph at the time (I think @non commented on the pain of that).

**Comment by non** [comment]
I like the idea of doing commit squashing. Especially when using Travis validation I feel like we often end up with a bunch of small commits that aren't that interesting. Ultimately the unit of "change" in Cats is the pull request, so syncing up the commits in *master* to fit that model seems good to me.

Does anyone feel strongly that we should not be doing this for *master*?

**Comment by non** [comment]
(Another nice thing about this is that it doesn't require people to rebase locally and use `push -f` in order to keep *master* history clean.)

**Comment by rossabaker** [comment]
Some longer running PRs may have multiple contributors, and it's nice to credit all the authors.  These are infrequent, but problematic for Squash 'Em All.  I'm neutral on the default policy but wary of a rigid one.

**Comment by non** [comment]
That makes sense. Maybe we should squash single-author PRs and use a more flexible policy for multi-author PRs.

**Comment by kailuowang** [comment]
We have been using squash PR merge for a while, generally it weird well. The only downside is that it will be harder to continue other work on a branch based off a branch that is not merged yet, since the history will be changed once it's squash merged. I haven't noticed such need (continue different work based off a yet to merge branch) in cats yet, but people should bear that in mind, if there is such case, they can request a PR to not use squash merge.
