### ISSUE TITLE
Map monoid appears to be slow.

### ISSUE THREAD

**Issue by easel** [typelevel/cats#1367]
I’m running into something interesting that seems to have changed unbeknownst to me in a cats upgrade. I have been combining Map[A, Map[B, Double]] with |+|. In the past, I had to provide a Semigroup[Map[B,Double]], which was good, because I implemented a sum of the doubles. However, recently, it appears as if an instance has showed up for Semigroup[Map[B, Double]].

I was able to eliminate the default implementations by only importing my Semigroup[Map[B, Double]] and cats.std.map._.

I'm in the process of determining if that resolves my performance issue or not now -- the reason I started down this rabbit hole was because a large batch computation that used to be fast got REALLY slow and all the stack traces appear to point inside of MapMonoid.

I am currently using cats 0.4.1.

**Comment by non** [comment]
This was fixed in https://github.com/typelevel/cats/pull/1300 and is available in 0.7.0.

https://github.com/typelevel/cats/blob/master/CHANGES.md#version-070

As a stop-gap you can pull in your own local version of `Monoid[Map[K, ?]]` if you need: https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/instances/map.scala#L26

**Comment by easel** [comment]
Thanks much for the pointer. I have pulled in the new monoid implementation and am running the integrations tests now. Fingers crossed!

**Comment by easel** [comment]
I can confirm the fix is good, and two orders of magnitude so. I haven't tried it yet with the dataset that has been blowing stack, but going to go ahead and close this anyway since it doesn't work to do.

Thanks for all the help @non!
