### ISSUE TITLE
ZipList and other newtypes

### ISSUE THREAD

**Issue by julien-truffaut** [typelevel/cats#1528]
Does cats as a policy regarding newtypes? I can't see any `ZipList`, `Conjunction`, `First`, `Last` and so on.

Do we want to define such a newtype in cats? if yes, would it be in core or another module? Otherwise, would you prefer a separate project like dogs?

**Comment by edmundnoble** [comment]
We need a cats-newtypes library first for an encoding.

**Comment by julien-truffaut** [comment]
We could start with an `AnyVal` case class and improve on that, WDYT?

**Comment by adelbertc** [comment]
I had originally thought that tagged types such as `scalaz.@@` were preferred to value classes due to differences in boxing behavior, but perhaps that has since changed? @tpolecat may know.

**Comment by tpolecat** [comment]
Yeah there need to be a cats-newtypes library and if it's not called `newts` I'm going to quit programming forever.

But I don't have any particular insight into `scalaz.@@`. I prefer it to `shapeless.@@` because the tag can't get lubbed away but it's a bit harder to use as a result. It's really awkward (try adding two maps using the `Minimum` tag for instance) and I have never once seen anyone get the zipping applicative to work. So as far as I'm concerned it's an unsolved problem.

**Comment by fthomas** [comment]
A year ago I set up a project to analyse and compare different tag types (https://github.com/fthomas/tagged), especially the boxing behaviour (wrt `AnyVal`s, `AnyRef`s, and `Array`s). Unfortunately I couldn't finish what I've started - that is adding more tag types and summarize the findings in a nice feature matrix. It would be awesome if someone could pick this work up and help us finding an appropriate representation for `newts`.

**Comment by julien-truffaut** [comment]
I created https://github.com/julien-truffaut/newts, I will try to expirement on newtype impl at the next hackathon

**Comment by julien-truffaut** [comment]
do you have an idea of how to benchmark different implementations? I guess we want to prove that a newtype is close to 0 runtime cost in particular when it is in collection.

**Comment by adelbertc** [comment]
I think a lot of "benchmarking" will just be looking at the bytecode to see how much boxing is happening.
