### ISSUE TITLE
Lack of whileM, whileM_, untilM and untilM_ methods for Monad

### ISSUE THREAD

**Issue by Atry** [typelevel/cats#1569]
These methods present in `scalaz.Monad`. Should we add them in cats as well?

**Comment by kailuowang** [comment]
Forgive my ignorance ( I never used these before),  I am just curious is there any usecases for this other than the `MonadState`, in particular, `MonadState[StateT[Trampoline, S, ?], S` (with Stack safety) or `MonadState[State[S, ?], S]` (without) .

**Comment by peterneyens** [comment]
There is this closed PR #1216 by @tpolecat (from before the move of `tailRecM` to `FlatMap`).

**Comment by tpolecat** [comment]
@kailuowang these can be useful for IO-like types, or things that will be interpreted into IO … in doobie for instance `get[Foo].whileM[Vector](next)` is a program of type `Free[ResultSetOp, Vector[Foo]]` that expresses the intent to read a resultset into a vector. 

I closed that PR because I lost interest in the tailRecM discussion, but it should be straightforward to implement now.

**Comment by Atry** [comment]
@kailuowang I am porting [ThoughtWorks Each](https://github.com/ThoughtWorksInc/each) to cats.

At the moment, [ThoughtWorks Each](https://github.com/ThoughtWorksInc/each) requires `whileM_ ` on `scalaz.Monad` in order to transform `do` and `while` loops.

I will be able to transform `do` and `while` loops on cats, if cats support `whileM_ `, too.

**Comment by johnynek** [comment]
Now that we have tailRecM on FlatMap these methods are easy (and stack
safe).
