### ISSUE TITLE
Document syntax and use of Simulacrum/Machinist

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#157]
I know that Simulacrum is still under active development, so we can hold off on this a bit until that settles if that's what makes sense.

I don't think I quite understand the full story of syntax enrichment in Cats. I know that Simulacrum and Machinist provide us with handy typeclass and ops enrichment.

But I don't know things like:
- Is our syntax bedazzlement currently in a state where it is free to use `1 |+| 2` as opposed to `Semigroup[Int].combine(1, 2)`?
- When (if ever) do I need to import things to get handy syntax from a type class and when (if ever) is it just automagically there?

I think @non and @mpilquist are the most knowledgable about this.

**Comment by stew** [comment]
So now that I've made #294 I'm more familiar. so the way things are in that PR:

We have syntax for <+> (among others), to get it you have to import either:
`cats.syntax.all._` or `cats.SemigroupK.Ops._` or cats.syntax.semigroupk._`

I'm using this as an example instead of |+| because we get semigroup from algebra, not from cats directly. there is still usable syntax there, just not from simulacrum, and thus there is no cats.semigroup.Ops.

We should have syntax for all the simulacrum managed stuffs, so for example, `fa map f` should work for anything that we have a Functor for when you have functor syntax in scope.

**Comment by ceedubs** [comment]
Someone has pointed out to me that @non has put together a detailed [explanation](https://gist.github.com/non/a6ff3c0796e566db20d1) of the benefit that Machinist provides beyond value classes. This is too detailed of an explanation to absorb into the Cats docs, but it might be a handy resource to link to.

**Comment by stew** [comment]
we aren't using machinist at all yet, right?

**Comment by non** [comment]
We are using Machinist in a few places currently (`EqOps` and `OrderOps`) and we should be using it in `SemigroupOps` as well. I've got a PR that will update those as well.

I don't know what the long-term picture for Simulacrum/Machinist integration looks like. In theory I'd like to use Machinist for all of our syntax where it is applicable, to improve the allocation/GC story. I'm not sure if most other Cats users/maintainers agree with this (and I do appreciate how much of this boilerplate Simulacrum can synthesize for us).

In any case, I'd be happy to try to create a document explaining *Interesting Syntax/Semantics* that Cats readers are likely to come across (I'm thinking of *kind-projector*, *simulacrum*, and *machinist*).

**Comment by diesalbla** [comment]
What would be the status of this issue? Currently, `simulacrum` is in Scala 2-maintenance mode, whereas `machinist` repo has been closed and incorporated into the `spire` project. At this point, and given lack of traction here, I would suggest closing this issue.
