### ISSUE TITLE
Group[Eval[A]] is not lawful

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats#1661]
Specifically, the inverse laws do not hold, for the same reason that they would not hold for `Group[IO[A]]`.  The problem is that `Eval` can (now) encode failure, meaning that it has values which cannot be eliminated.  Simple counter-example:

```scala
val zero = Group[Eval[Int]].empty
val example = Eval.raise(new Exception)

example.inverse |+| example === zero   // nope!
```

In the above, `example.inverse |+| example` will be equal to `Eval.raise(new Exception)`, which is clearly incorrect.

Basically, `Group` and `ApplicativeError` are mutually exclusive.  You can't have both of them at once.  If you want `Eval` to implement `MonadError`, then it can be at most a `Monoid`, but not a `Group`.

**Edit** See below.  `Group` is the least of the problems.

**Comment by djspiewak** [comment]
As a sidebar, and perhaps worthy of another issue, the reason this unlawfulness is not caught by the current tests is [the generators](https://github.com/typelevel/cats/blob/master/laws/src/main/scala/cats/laws/discipline/Arbitrary.scala#L95-L99) do not include `Eval.raise`, meaning that we're just not checking the full space of `Eval` instances.  This should *also* be addressed, and will force a resolution to the OP.

**Comment by ceedubs** [comment]
Good catch @djspiewak. I don't think that we should have an `ApplicativeError` instance for `Eval` (and probably not even a `raise` method) without including `Eval.raise` instances in `Eval` generators. I wouldn't be surprised if doing so would identify more instances that aren't lawful, and that would leave us with a choice as to whether we want to drop those instances or drop the error-capturing component of `Eval`. Personally I'm not sold on the error-capturing behavior (especially now with the existence of cats-effect), but I've voiced that concern before, so I won't hammer on it :)

**Comment by djspiewak** [comment]
I'd be fine with or without the error capturing behavior, though `cats.effect.Sync[Eval]` will not be lawful if it doesn't capture errors.  We just can't have that behavior *and* have `Group[Eval[A]]`, so it's a tradeoff that needs to be weighed.

**Comment by edmundnoble** [comment]
For the record I'm also in favor of removing the error capturing behavior, especially seeing how it would interact with the stack-usage optimization I have; sacrificing individual stack frames becomes sacrificing `n` stack frames. The idea that an `Eval` I'm holding might carry an `Exception` makes it much harder from a library perspective to use it. 

@djspiewak `CommutativeMonoid[Eval[A]]` also fails, because for two error-containing `Eval`s adding one to the other always retains the *first* exception.

**Comment by djspiewak** [comment]
> CommutativeMonoid[Eval[A]] also fails

That is correct, but `Monoid[Eval[A]]` is fine.

**Comment by edmundnoble** [comment]
I didn't say it wasn't :wink:

**Comment by djspiewak** [comment]
Actually, a ton of stuff breaks when you try to fix this:

```
[error] 	cats.tests.NonEmptyVectorTests
[error] 	cats.tests.OneAndTests
[error] 	cats.tests.EitherTTests
[error] 	cats.tests.EitherKTests
[error] 	cats.tests.NonEmptyListTests
[error] 	cats.tests.EvalTests
[error] 	cats.tests.StateTTests
```

So I went hunting a bit and found things like [this](https://github.com/djspiewak/cats/blob/master/core/src/main/scala/cats/Eval.scala#L440-L444), [this](https://github.com/djspiewak/cats/blob/master/core/src/main/scala/cats/Eval.scala#L429-L433), [this](https://github.com/djspiewak/cats/blob/master/core/src/main/scala/cats/Eval.scala#L418-L422), and [this](https://github.com/djspiewak/cats/blob/master/core/src/main/scala/cats/Eval.scala#L394-L416).  Basically, there's a ton of stuff which simply isn't lawful and *can't* be lawful if `Eval` has a `MonadError` instance.

I really think it should be removed.

**Comment by djspiewak** [comment]
Separating into a second comment, just so the discussion can be a bit more discrete…

I think this is a consequence of conflating two design goals with `Eval`: abstracting over evaluation semantics and abstracting over partiality.  Instances like `Eq` and `Group` are really only lawful if the underlying computation is total.  The moment we start doing anything partial at all, we run into trouble.  This is true even just by using `Eval` as a trampoline (i.e. where `value` becomes a partial function that is potentially non-terminating) but it becomes *brutally* apparent once we take the next logical step of adding error handling and the ability to encapsulate exception-throwing partial functions.

Given that we generally hand-wave our way past unbounded recursion, I'm basically ok with leaving `Eval`'s trampoline functionality intact.  It's still technically part of the same problem domain, but it's unlikely to cause real problems in practice.  However, partiality via exceptions is clearly beyond the pale here.  There's just no way to have our cake and eat it too.  Either `Eval` is something very effect-like (basically, a synchronous `IO`) and it cannot in any way sanely define things like `Eq[Eval[A]]` or `Group[Eval[A]]`, or it is a way of abstracting over evaluation and stack-safety, in which case it cannot encode any partiality (other than potentially unbounded recursion).

**Comment by edmundnoble** [comment]
Agreed on all points. :+1:

**Comment by johnynek** [comment]
yeah, I think `Eval[A]` having the `MonadError` is certainly not worth all the downsides we are discussing here. I agree that the existence of cats-effect reduces the need for `Eval` to have this instance. I think if you want a `MonadError` with defer, you should be using IO or something else.

**Comment by kailuowang** [comment]
also 👍 on removing the `MonadErorr` instance.

**Comment by alexandru** [comment]
I'm 👎  on removing the `MonadError` instance. Some problems we've seen can be solved with a better internal encoding, because an encoding that does `throw ex` internally is clearly problematic.

The `cats.effect.IO` cannot be a substitute for `Eval` because `IO` is asynchronous.
In other words `Eval` is a `Comonad` whereas `IO` cannot be a `Comonad`.

And if we remove `MonadError` from the `Eval` implementation, the only thing that we'll accomplish is a corresponding `SyncIO` that will happen eventually in `cats.effect` or elsewhere, duplicating the work and the confusion.

And I'm all for lawfulness, but in absence of a `MonadError` you can still do this:

```scala
val zero = Group[Eval[Int]].empty
val example = Eval.always(throw new Exception)

example.inverse |+| example === zero   // nope!
```

So by not implementing a `MonadError`, we are only depriving users of recovery tools, while pretending that the lawfulness in this case actually matters.

**Comment by ceedubs** [comment]
> The cats.effect.IO cannot be a substitute for Eval because IO is asynchronous.
In other words Eval is a Comonad whereas IO cannot be a Comonad.

I don't see `cats.effect.IO` as being a substitute for `Eval`. I see `IO` as being an error-capturing mechanism for deferred (and potentially async) side effects. I see `Eval` as being a stack-safe abstraction for strict/lazy/byname parameters. When `Eval` is used as this, it does in fact form a valid `Comonad` as you have mentioned.

It conflicting to claim that `Eval` forms both a `Comonad` and a `MonadError`. If you construct an `Eval[A]` instance via `raiseError`, you can't get an `A` out of it.

It's true that you can break just about any instance by putting `throw new Exception` in your code. `Either[Throwable, ?]` has a completely valid `MonadError` instance, but you still are going to run into trouble if you `throw e` as opposed to using `raiseError(e)` when working with `Either`.

**Comment by kailuowang** [comment]
👍  on @ceedubs' comment above. I've been thinking of `Eval` as an "abstraction for strict/lazy/byname parameters". 
As a user, I do want something that can handle the "exception being thrown" effect, but it never occurred to me that I can `Eval` as a monad for that, doesn't feel right to me. 
Usually such "exception being thrown" effect happens at the boundary of the system where my code has to deal with some other impure library. Very often such boundaries are also IO boundaries, and we all know what monad to use with that.  In other cases, I'm used to use a `Try`, and if I don't like try I just transform it to an `Either[MyErrorADT, ?]`.  I don't want to deal with `Throwable` anyway.

**Comment by djspiewak** [comment]
@alexandru I think that Cody really nailed it on the head here:

> It's inconsistent to claim that Eval forms both a Comonad and a MonadError. If you construct an Eval[A] instance via raiseError, you can't get an A out of it.

It's very important that `Eval` forms a comonad.  That's a large part of why it's useful!  As you said, `IO` *cannot* form a comonad, but that would be true even if it didn't have an `async` constructor.  `IO` cannot be a comonad any more than `Either` can be, and for exactly the same reasons.

Your example of violating the group laws is certainly true.  But I can violate any law by passing non-functions to things that expect functions.  By enriching `Eval` with error handling behavior, we were extending the space of Scala functions it can accept to include those which throw exceptions.  But as it turns out, this behavior is inconsistent.  So rather than try to solve that inconsistency (and, given the isomorphism to `Either`, there is a trivial proof that it is fundamental and unsolvable), we're just contracting the space again.  `Eval` is only lawful on total functions, as with most of Cats.

So at the end of the day, there's really nothing for it: `Comonad` and `MonadError` are mutually exclusive.  If you need `MonadError`, use `IO` (or similar).  If you need `Comonad` (as all the major use-cases for `Eval` do!), use `Eval` but don't expect error handling.  If you need error handling in your `Eval`, use `Try` or something.

**Comment by adelbertc** [comment]
👍 on removing `MonadError` instance for the same reasons stated previously:

* `Eval` was designed for evaluation strategy - giving it a `MonadError` instance and piggybacking on it's laziness was always weird to me
* It is inconsistent to claim something as `Comonad` and `MonadError`

**Comment by johnynek** [comment]
This is where FP in scala becomes a challenge.

1. it is true, that an `Eval[A]` may throw on evaluation. There is almost nothing we can do to stop that since who knows what exceptions might be triggered by running this. That said, we recommend that if you follow best practices that will be very rare (don't call java code without try/catch and null checks, don't call methods that may stack overflow inside your Eval).

2. if we introduce `Eval.raiseError` it clearly conflicts with Comonad.

What about a middle way?

We could have a type like
```scala
case class EvalError[A](eval: Eval[A]) {
  // way to get back to Eval (somewhat)-safely
  def recoverToEval(t: Throwable => A): Eval[A]
}

object EvalError {
  def raiseError[A](e: Throwable): EvalError[A]
}
```
and then we could have `MonadError[EvalError]` and no `Comonad[EvalError]` or `Group[EvalError]` etc...

To me, this seems like a good way forward.

**Comment by alexandru** [comment]
`EvalError` is an ugly name :-)

I do think having a `MonadError[Eval]` is more useful than a `Group[EvalError]`. But if you really think this is the right approach, then don't let me block the removal of `MonadError`.

**Comment by adelbertc** [comment]
I don't think we should privilege `Eval` like this. I would prefer just dropping the instance.

> it is true, that an Eval[A] may throw on evaluation. There is almost nothing we can do to stop that since who knows what exceptions might be triggered by running this
Do you mean currently with `MonadError` or in general?

**Comment by djspiewak** [comment]
@johnynek We technically already have what you're talking about in a more general form with `EitherT`, which is to say, the `FreeMonadError`.  There exists a `MonadError[EitherT[F, E, ?], E]` for all `E` and all monads `F[_]`.  Thus, `type EvalError[A] = EitherT[Eval, Throwable, A]`.

**Comment by johnynek** [comment]
Indeed. @djspiewak but I think we need to do something about `Eval.defer` which seems a bit tricky to get on this `EitherT`: you need to unwrap the `EitherT` to pass it to `Eval.defer` but by the time you can do that, you will have evaluated the thunk.

I think you will need to reach under the hood to do this. Maybe we could add a method like:

```scala
def deferError[E, A](e: => EitherT[Eval, E, A]): EitherT[Eval, E, A] = ...
```
Maybe I'm wrong and you can implement that using the public API, but I didn't think so on a quick look.

**Comment by johnynek** [comment]
maybe something like:
```scala
def deferEitherT[E, A](e: => EitherT[Eval, E, A]): EitherT[Eval, E, A] = 
  (new Eval.Call[Eval[Either[E, A]](() => e.value) { }).map(EitherT(_))
```
maybe there is something general here about
```
def deferMap[E, T](e: => E)(fn: E => Eval[T]): Eval[T] =
  new Eval.Call[Eval[T]](() => fn(e)) { }
```

**Comment by johnynek** [comment]
@adelbertc to answer your question: I meant in general. Like I could do:

```scala
val str: String = someStr()
Eval.later(str.toInt): Eval[Int]
```
or something similar without noticing (by calling some unsafe or buggy method that you didn't realize). I think that is not good code unless you have some proof that the String really only contains an Int which is not easy to express in the type system currently.

**Comment by adelbertc** [comment]
`str.toInt` is not a function so I do not consider it something we should be concerned about. If we did, then to be consistent `Monad[Try]` would be invalid.

**Comment by edmundnoble** [comment]
If we keep a `MonadError` for `Eval`, I want to see a `Comonad` for `Either` and `Option`. 

All of the instances in cats are *consistent* with regard to Exception-proofing: you cannot, using any combination of any methods from any type class instances for a given type end up with an `Exception` thrown. Just because Scala is not perfect with regard to side effects and the type system does not mean we need to throw the baby out with the bathwater and provide users with one special `Comonad` instance that completely breaks the rules. This would make actually *abstracting* over an arbitrary `Comonad` impossible because hey, what if it's a *throwing* `Comonad`? Then you have to wrap `extract` in `try`, and if your code doesn't care about the errors from one of these *throwing* `Comonad`s you need to somehow absorb or catch the errors in what is likely otherwise pure code and... at the end of it all, there isn't even a reason to treat `Comonad` specially here. This same argument applies to every method in every type class in cats and would make cats impossible to use safely if applied consistently. You break the rules by putting `throw` in an `Eval`, *you* pay for it.

**Comment by johnynek** [comment]
So, folks. I know we all love to show we are each more lawful than the
next. But don't we have almost total unanimity here?

**Comment by edmundnoble** [comment]
Looks like. Though @ceedubs and I are curious about @non's position.

**Comment by alexandru** [comment]
Just throwing some wood on fire 😄 but I think one of the motivations for `MonadError` was usage of `catchNonFatal`.

See this discussion about my original `ApplicativeEval` proposal: https://github.com/typelevel/cats/pull/1552#issuecomment-285730625

In other words without `MonadError` the `Eval` data-type will not implement `Sync` and `Applicative.pure` takes a strict parameter, a problem that Haskell and Scalaz do not share.

So we have absolutely no way currently to abstract over `Eval.always` and `Eval.defer` (or `Future.apply` for that matter).

**Comment by alexandru** [comment]
Also currently `Eval.raise(e)` is literally implemented as `Eval.always(throw e)`.

And this matters because the user can implement its own `MonadError` without modifying `Eval` and it will be a lawful implementation.

So if Cats is not providing a `MonadError` implementation, that does not mean that `Eval` doesn't accept a `MonadError`, because it does.

In other words, if `Group[Eval]` is incompatible with `MonadError[Eval]`, then maybe `Group[Eval]` should not happen, regardless if Cats provides a `MonadError[Eval]` by default or not.

**Comment by alexandru** [comment]
And let me make an analogy: for the sake of argument, lets say that Cats wouldn't be providing a `Monad[Eval]` instance. But that doesn't mean that `Eval#now` + `Eval#flatMap` isn't a `Monad` anyway.

**Comment by johnynek** [comment]
That's true, but the situation may be a bit like List and ZipList. You can
choose to make the Cartesian on List use zip instead of Cartesian product,
but once you do you can't have a Monad.

So a user could make such an implementation the applicative, and when they
want Applicative they get one thing and Monad they get another. This is
probably not what should happen but scala does not have coherent
typeclasses.

I think the argument may be that as soon as you `throw` all bets are off.
So the user can implement a MonadError by using throw with Eval, but cats
position may be that who knows what laws will break because of that.

To turn it around, any lazy parameter a user may throw, many laws might
break then. We should not remove all instances that are not lawful under
throw since pretty much anything will fail that test.

**Comment by djspiewak** [comment]
@alexandru I'm with @johnynek on this one: if you implement something by using `throw`, you're beyond the pale.  It's relatively easy to implement unlawful things (and break other laws) by using functions that are not functions.  `Eval` just doesn't have semantics surrounding exceptions.

We can implement `Sync[EitherT[Eval, Throwable, ?]]` in a way which is lawful.  Which is to say, `Sync.delay(throw t)` would behave the way you would expect.  And I suspect that we will do exactly this in cats-effect.
