### ISSUE TITLE
Could we add !== to mean Eq#neqv?

### ISSUE THREAD

**Issue by ctongfei** [typelevel/cats#1664]
Currently we have `=!=`. Could we add `!==` also because this 3 characters is implemented as a ligature in fonts like Fira Code, making it better looking.

![](https://github.com/tonsky/FiraCode/raw/master/showcases/all_ligatures.png)

**Comment by edmundnoble** [comment]
No, we can't. `!==` has different operator precedence than `===`, `=!=` and `==`. This just needs to be added to Fira; see https://github.com/tonsky/FiraCode/issues/338. Also see http://stackoverflow.com/questions/2922347/operator-precedence-in-scala: "Operator precedence is fixed in the Scala Reference - 6.12.3 Infix Operations by the first character in the operator."

**Comment by ctongfei** [comment]
Thanks :-)
