### ISSUE TITLE
Rename `traverse_` and `sequence_` in Foldable

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#1723]
I realize the underscore comes from the Haskell equivalent, but I do not believe it conveys its intent. 
The two functions do the same as their non-underscore counterparts, but ignore the result returning `F[Unit]`.

I suggest something along the lines of `traverseVoid` or `traverseToUnit`. 

This would also affect the `Reducible` type class and its non empty counterparts.

Edit: Something to keep in mind, is that these two methods are already being renamed in `Reducible` as part of #1611 (`traverse1_` -> `nonEmptyTraverse_`). So we're going to be breaking the API anyway. I think it would make a lot of sense to use this opportunity to rename these and give them a better name.

**Comment by diesalbla** [comment]
##### Alternative Proposal 

The type-class `Functor` provides a function `void`, which transforms an `F[A]` to an `F[Unit]`; and the syntax class for `Functor` already provides it. Thus, you can write `xs.traverse_( foo)` as `xs.traverse(foo).void`. 

Following the In orthogonality principle, and since `.void` is just 5 characters, I would suggest directly removing the methods `traverse_` and `sequence_`.

**Comment by LukaJCB** [comment]
I have to disagree there, `traverse` has a `Traverse` typeclass constraint, while `traverse_` only requires `Foldable`.

**Comment by diesalbla** [comment]
You are right. I just thought, by the similarity of the names, that the `traverse_` method would be defined in the `Traverse` type-class, but I was wrong and that is not the case.

I agree they should be renamed, but I would avoid using the word `traverse` in the new names. Since the goal is to iterate through each element in the collection in order, perform an _action_ (a `Unit` value with an effect), I would then suggest calling them `foreach` or `foreachDo`, or `foldEach`; that would be closer to the same-named methods in the `List` class of the standard library.

**Comment by LukaJCB** [comment]
I think it makes sense to keep the `traverse` and `sequence` naming scheme as it's well established by now. I just disagree with the underscore. We could also think about calling it `traverseIgnoreResult` or something along these lines.

**Comment by ceedubs** [comment]
I think that something like `traverseVoid` is probably a bit better than `traverse_`. However, I personally don't feel strongly enough about this to make an API change. I'm open to others' opinions on this. @johnynek you are someone who has requested that we don't change APIs in the past. Do you have any thoughts on this?

**Comment by mdedetrich** [comment]
I actually like the name of `traverseUnit` as it sounds more idiomatic with Scala. However @diesalbla has a point, in which case if you wanted to follow examples for stdlib you would call it `foreach` (if this is an argument)

**Comment by diesalbla** [comment]
The names for `traverse` and `sequence` are well established in the [reference literature](http://dblp.uni-trier.de/rec/bibtex/journals/jfp/GibbonsO09), from the Haskell libraries. However, I would not use at all the word _traverse_ in the name of this method, because it misleads into assuming a  link to the `Traverse` typeclass that, as @LukaJCB rightly pointed out, does not exist. 

It is worth noting that, as discussed [here](https://ghc.haskell.org/trac/ghc/wiki/Prelude710/FTP?version=14), the Haskell libraries did not include a `Foldable` (or `Reducible`) typeclass until a recent version, long after the first release. Presumably, that is why this method was in the `Traverse` type-class at first, and hence their names. That being the case, since `cats` is not (yet) released, IMHO we should take the chance not to use the words _traverse_ or _sequence_ for this methods.

Apart from `foreach` for `traverse_`, I would also suggest using `doAll` for `sequence_`.

**Comment by mdedetrich** [comment]
Also we shouldn't just be copying Haskell in this regard, because both libraries have different naming schemes. The most obvious is how `map`/`flatMap` is called in Scala is completely different to how its called in Haskell.

I think the attempt should be for cats to actually try and use Scala's idiomatic naming scheme, in which case `foreach` is probably what we want.

**Comment by SystemFw** [comment]
Using the same name as the standard library means that `syntax` stops working.
Now you can do `List(1,2,3).traverse_(a => IO(println(a))`, if you change `traverse_` to `foreach`, the existing stdlid method will be selected, forcing you to do `Foldable[List].foreach(List(1,2,3))(a => IO(println(a))`.
For this reason, I think `cats` should actually strive to _not_ call things like in the stdlib

**Comment by diesalbla** [comment]
@LukaJCB Are you still interested in pushing for this?

**Comment by rossabaker** [comment]
Didn't achieve critical mass, and the names are further entrenched now.  Let's close it.
