### ISSUE TITLE
Macros to Generate Laws-Tests Boilerplate

### ISSUE THREAD

**Issue by diesalbla** [typelevel/cats#1727]
This issue concerns the coding of the `Laws` traits, in the SBT-project `laws`, in the folder `laws/src/main/scala/cats/laws/`. I have noted that all of the laws-files in this folder follow a similar structure. Thus, for a type-class named `Foo`, the laws for this type-class, in the file `FooLaws.scala`, looks like this: 
```Scala
trait FooLaws[F[_]] extends BarLaws[F]{
  implicit def F: Foo[F]

   def fooLaw1[A,B,C](....)
   def fooLaw2[A,B,C](....)
   [... actual laws...]
}

object FooLaws {
  def apply[F[_]](implicit ev: Foo[F]): FooLaws[F] =
    new FooLaws[F] { val F = ev }
}
```
This design has some boilerplate for the code and the names of methods. The same is true of the `Tests` files in each set of laws, those in folder `/laws/src/main/scala/cats/laws/discipline/`. For the same type-class, the file `FooTests` file be the following:  
```Scala
trait FooTests[F[_]] extends BarTests[F] {
  def laws: FooLaws[F]
  [... actual tests]
}

object FooTests {
  def apply[F[_]: Foo]: FooTests[F] =
    new FooTests[F] { def laws: FooLaws[F] = FooLaws[F] }
}
```

The proposal of this issue is to create a pair of macro annotations, `@laws` and `@testlaws`, to generate that boilerplate code. Its use would reduce the actual code in the file `FooLaws.scala` to the following: 
```Scala
@laws
trait Foo[F[_]] extends Bar[F]{
   def law1[A,B,C](....)
   def law2[A,B,C](....)
   [... actual laws...]
}
```

Whereas the code in the file `FooTests.scala` would be reduced to the following: 
```Scala
@testlaws
trait Foo[F[_]] extends Bar[F]{
   [... actual tests...]
}
```

**Comment by kailuowang** [comment]
I am 👍  for using a macro to generate the trait instance summon code i.e. ` def apply[F[_]](implicit ev: Foo[F]): FooLaws[F] = new FooLaws[F] { val F = ev }`
I am not sure how I feel about replacing the simple type class instance field i.e. `implicit def F: Foo[F]`, that's not a lot code to read, but without it, people might get confused reading the laws without further investigating what the macro does.  
In the `Tests` class though, I am less concerned with replacing `def laws: FooLaws[F]` with macros, though, mainly because this whole tests class is pure boilerplate. In a perfect world, the tests class should probably entirely auto generate but that seems extremely tricky in reality, given all the custom tests and tests subtyping.

**Comment by diesalbla** [comment]
Given that the use of Macros in Scala may be on the way out, it seems this won't be going forward.
