### ISSUE TITLE
Ior biased pattern matchers

### ISSUE THREAD

**Issue by fommil** [typelevel/cats#1742]
any interest in adding these sorts of pattern matchers?

```
  object Lefty {
    def unapply[L, R](ior: Ior[L, R]): Option[(L, Option[R])] = ior match {
      case Ior.Left(left) => Some((left, None))
      case Ior.Both(left, right) => Some((left, Some(right)))
      case Ior.Right(_) => None
    }
  }
```

as a workaround to scala's lack of combining extractors, e.g.

```
foo match {
  case Ior.Left(left) | Ior.Both(left, _) => left
  case Ior.Right(_) => fallback
}
```

bonus: also provides easy access to the `.right` if the `Ior` is no longer visible.

**Comment by fommil** [comment]
of course, the other way to do this is with `.left match` ... so maybe this is not needed.

**Comment by sellout** [comment]
Despite @fommil closing this, I still think something like `Lefty` is useful (SlamData has implemented it as `HasLeft`). However, I don’t think the `Option[R]` is helpful. If you’re going to care about _maybe_ having the right side, it’s safer to just explicitly match on `Left` / `Both` / `Right` rather than trying to use extractors.

**Comment by sellout** [comment]
Our impl:
https://github.com/sellout/quasar/blob/remove-old-Mongo/foundation/src/main/scala/quasar/contrib/scalaz/package.scala#L27

**Comment by fommil** [comment]
btw, does anybody know if there is an SI- number for pattern matching like this?

**Comment by fommil** [comment]
https://github.com/scala/bug/issues/182
