### ISSUE TITLE
a "works with cats" badge

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1807]
So that projects that integrate with cats can use.

**Comment by DavidGregory084** [comment]
You can create custom badges on shields.io:

![custom badge](https://img.shields.io/badge/works%20with%20cats-1.0.0--MF-green.svg)

**Comment by thoefer** [comment]
![versions](https://user-images.githubusercontent.com/202410/43990285-4b8301da-9d5a-11e8-82d5-6abb858b2dd6.png)

**Comment by thoefer** [comment]
proposals, hints, suggestions?

**Comment by milessabin** [comment]
:+1: for "Cats friendly".

**Comment by johnynek** [comment]
👍 cats friendly, but I like using the hexagonal cat vs lambda, which I think is more distinctive (lambda being very generically used across FP).

**Comment by BennyHill** [comment]
Cats friendly + hexagonal cats => :+1:

**Comment by davegurnell** [comment]
+1 for hexagons and "cats friendly" :)

If people are interested I could speak to Jenny, the artist for the Scala with Cats book (http://underscore.io/books/scala-with-cats). She's more of a comic book artist and IMO what's needed here is pixel art, but I can have the conversation and see what she says.

**Comment by thoefer** [comment]
@davegurnell Polishing an icon at the pixel level is what I usually do last. Right now the interpolation is somehow arbitrary and not optimized for being show at this small size. The end result is a more crisp icon, what you maybe expect. Nevertheless: I'd not consider that final icon to be "real" pixel art.

**Comment by thoefer** [comment]
![versions2](https://user-images.githubusercontent.com/202410/44302850-8f6fe480-a331-11e8-8142-f227e2a7c5ed.png)

The design process flows (as usual; at least for me) from top left to right bottom. In the first half of everything I tried a pictographic cat, which I abandoned at some point. I simply tried a view concepts. In the final pieces on the right, especially bottom-right I tried to visually resolve the dualism between cat and hexagon by integrating the former into the last. Actually I like how it turned out.

**Comment by thoefer** [comment]
![cats_friendly_big](https://user-images.githubusercontent.com/202410/44628798-b341b480-a947-11e8-966f-ce1e121d78ad.png)
![cats_friendly_normal](https://user-images.githubusercontent.com/202410/44628799-b341b480-a947-11e8-97a2-267b60707b6c.png)
![cats_friendly_tiny](https://user-images.githubusercontent.com/202410/44628800-b341b480-a947-11e8-9412-6a6ef3fba05e.png)

@kailuowang Does that come close to what you had in mind?

**Comment by LukaJCB** [comment]
That looks great @thoefer :)

**Comment by thoefer** [comment]
Thanks @LukaJCB !

**Comment by thoefer** [comment]
I can extract the polycat from the badge, no problem.

**Comment by thoefer** [comment]
Good idea with adding it to the repo, I'll do that asap.

**Comment by thoefer** [comment]
![cats_friendly_big](https://user-images.githubusercontent.com/202410/45928044-6dbfd980-bf3d-11e8-9159-14408d81f975.png)
![cats_friendly_normal](https://user-images.githubusercontent.com/202410/45928045-6dbfd980-bf3d-11e8-863d-2679b143ee55.png)
![cats_friendly_tiny](https://user-images.githubusercontent.com/202410/45928046-6dbfd980-bf3d-11e8-8693-c1285dae03ce.png)

Can we agree on that these are the final versions of the badge? I rebuilt the original cats logo from scratch as @non does not seem to have the original version of the logo available. I´ll create another pull request in order to add the logo to the repo.

**Comment by calvinbrown085** [comment]
Hi @kailuowang I made a PR https://github.com/typelevel/cats/pull/2554 that adds the new "cats friendly" badge to the README, do you think this PR addresses this issue as well?

**Comment by thoefer** [comment]
Thanks @calvinbrown085 !!

**Comment by ceedubs** [comment]
This should be resolved by #2554.
