### ISSUE TITLE
Clarify in README that cats is an experimental clone/rewrite of scalaz

### ISSUE THREAD

**Issue by BennyHill** [typelevel/cats#1823]
See https://github.com/fommil/fp-scala-mortals/blob/fd4b278e71624ac97579ac241f77a8e06ac34d78/manuscript/frontmatter.md

**Comment by johnynek** [comment]
cats is a library for standard FP type classes in scala. It has a number of overlaps with scalaz, and in many cases uses code originally derived from scalaz, but there are a considerable number of different design choices.

**Comment by adelbertc** [comment]
This is not accurate. Cats started as a new project because its developers wanted the flexibility to explore different design choices outside of those made in Scalaz. For example, the encoding of laziness in a data type (`Eval`, or as it was known at first, [`Lazy`](https://github.com/typelevel/cats/blob/v0.1.0/core/src/main/scala/cats/Lazy.scala)) instead of by-name arguments, as well as the attempted modularization (`core`, `free`, `state`). By virtue of being in a the similar functional-programming-in-Scala space as Scalaz there is bound to be a significant overlap, and in some cases we did copy files files from Scalaz (e.g. `FreeT`). Therefore I don't think it is accurate to say Cats is a clone of Scalaz.

**Comment by fommil** [comment]
The title of this issue is disingenuous: it is not a fair representation of how I'm describing cats.

I describe cats as "an experiment to rewrite scalaz". This is true. Experiment breeds innovation. At this point in time, 1.0 is not yet released. The coming years will let us know if the experiment has been worth all the strife and the split in the community.

I also write "the cats API is mostly a clone of scalaz, so this book is relevant for either library". Given that rewriting the demo app from cats to scalaz consisted of changing the imports plus a one line code change, I stand by this statement.

I took input from several Typelevel contributors and conference slides when drafting the descriptions. I feel the description is fair and accurate. I am certainly not introducing Typelevel as "a hostile fork of scalac and scalaz" as my previous employer's senior management describe it.

If 1.0 is released and there are download statistics to suggest that cats has overtaken scalaz, I may change the description to something like "cats began as an experiment to rewrite scalaz and is now a popular alternative."
