### ISSUE TITLE
[Proposal] new `cats.experiment` module 

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1941]
Post 1.0, cats will lock the API for a long time. In the meantime, we might want to add new features that are not yet battle tested. 
I propose to create a new `cats.experiment` module (It can be in a separate repo, but that will increase the burden of maintenance) to place novel and complex features that are not battle tested in the FP world. 

As the name suggests, has no guarantee of backward compatibility going forward, features can graduate from here to other appropriate mature modules, core, free, extra or a new module as we see fit. We would recommend against libraries with downstream dependencies from using this `cats.experiment` module. Things here don't have to be placed under a `cats.experiment` package though, they can be place in more appropriate target package they intend to go after graduation. This would ease migration.

**Comment by tpolecat** [comment]
I think I prefer this kind of thing be done by individuals or sub-groups (as was done for `cats-effect` and `cats-mtl`) rather than creating a wild west module. With no guiding or organizing principle I fear it will lead to a lot of mutually-inconsistent stuff and dead ends that never get cleaned up. It has Wiki nature (and not in a good way).
