### ISSUE TITLE
Remove `Eq.and`, `Eq.or`, `Eq/PartialOrder/Order.on`, `PartialOrder/Order.reverse`

### ISSUE THREAD

**Issue by denisrosset** [typelevel/cats#1995]
These methods are quite unusual in the sense that `Eq`, `PartialOrder` and `Order` are (to my knowledge) the only typeclasses to have direct methods to derive instances. IMHO, these methods belong to the companion objects.

In particular, `on` is a nightmare to override consistently in hierarchies that inherit from `Eq`. For example, currently `(h: Hash[A]).on[B]` returns `Eq[B]`, not `Hash[B]`, while `Hash.by` does the right thing.

And the methods `Eq.and`, `Eq.or` are confusing when `Eq` should be actually a coherent typeclass.

Thus, I propose to remove them. If compatibility is needed, they can be provided by enrichment methods.

Edit: if there is interest, I will propose a PR, but I don't know where `cats-kernel` stands binary compatibility wise.

**Comment by kailuowang** [comment]
+1 on moving them to companion

**Comment by johnynek** [comment]
I don’t think actually have a policy that we assume coherent instances and as such don’t want combinator methods on typeclasses.

I personally would love if scala has coherent typeclasses you can only define in companions of either the type or the typeclass but it doesn’t and in the mean time things like Order.reverse are useful in sorting applications.

The subclass argument is a good one to me, but I would move the method into the companion so it is still easy to contramap these types.

**Comment by ctongfei** [comment]
This is the problem of branching subtypeclasses.
Hash <: Eq; Order <: Eq.

If we have `Hash[B]#on[B](f: B=>A): Hash[B]`, then something that extends `Hash` and `Order` will have to override `on` because there is already `Order[A]#on[B](f: B=>A): Order[B]`.

I agree that `on` methods could probably be removed, because once we import `cats.implicits.all` we should have the injected `contramap` method because of their existing `Contravariant` instances.

Should `Eq` be a coherent typeclass? Sometimes we can have different equivalence relations endowed on the same type. I don't think that making `Eq` coherent is a good idea.

**Comment by kailuowang** [comment]
So @johnynek  will it be okay to break kernel back compat with this change (i.e. moving them to companion)?

**Comment by johnynek** [comment]
@kailuowang from the algebird side, we are using the algebraic typeclasses. These equality ones, not at all yet.

**Comment by LukaJCB** [comment]
Fixed by #1997! Thanks @denisrosset! :)
