### ISSUE TITLE
MonoidK for Function1 should be consistent with Kleisli

### ISSUE THREAD

**Issue by SystemFw** [typelevel/cats#2025]
When dealing with #1928 , no one mentioned that the instance of `MonoidK` for `Function1` exhibits the exact same problem. It should be changed to be consistent with the Kleisli instance.
The current behaviour for Function1 (and old behaviour for Kleisli) should be on an `Endo` newtype.

@tpolecat

**Comment by tpolecat** [comment]
Yep. If we do this it would be nice to have `EndoK` also. Scalaz has an `Endomorphic` typeclass but like other arrow stuff I don't get the feeling it's used much. I'm ambivalent about taking it that far.

**Comment by kailuowang** [comment]
@tpolecat just to be clear by `EndoK`, did you mean endo `FunctionK`? so we need 3 new types in total for `Function1` `Kleisli` and `FunctionK`. what would be the usage of `EndoK`?

**Comment by tpolecat** [comment]
`Endo[A]` is `A => A` has a monoid with `andThen` and `identity`.

`EndoK[F[_], A]` is `A => F[A]` and has a monoid with `>=>` and `pure`.

It's not super critical but I have needed it a few times.

**Comment by kailuowang** [comment]
This might be a non issue. 
We can't have a `MonoidK[A => ?]` that combines the return value of A => ?, since we don't know the return type we can't require a `Semigroup` on ?  
So the current `MonoidK[λ[α => Function1[α, α]]]` is the only `MonoidK` we can have for `Function1`
We also have `Monoid` and `Semigroup` instances for `Function1` that combines the return values. If we need a `Monoid[λ[α => Function1[α, α]]]` that uses `compose` for `Monoid.combine` , we can just call  `MonoidK[λ[α => Function1[α, α]]].algebra`

`EndoK` can be a separate issue.

**Comment by SystemFw** [comment]
I have reached pretty much the same conclusion, fwiw

**Comment by tpolecat** [comment]
Fine.
