### ISSUE TITLE
Remove `Applicative#traverse` and `Applicative#sequence`

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2039]
These don't really serve any purpose and just delegate to the functions on `Traverse` so let's get rid of them.

**Comment by travisbrown** [comment]
As a little extra motivation, if you try to call `traverse` on something like `catsStdInstancesForVector` with type parameters, the compiler will complain about the middle parameter not having the right kind (because of the collision between `Applicative#traverse` and `Traverse#traverse`). You can easily work around this by upcasting the instances, but it's still vaguely annoying.

**Comment by kubukoz** [comment]
I think I can make this happen ;) always calling dibs on removing some code

**Comment by jtjeferreira** [comment]
If anyone is missing the `Applicative#sequence` when use in a composed Applicative like in `Applicative[Future].compose[MyValidatedNel].sequence(segments)`, then an workaround described in 
https://gitter.im/typelevel/cats?at=5a564e2f232e79134dedaad5
