### ISSUE TITLE
Abstract Method error

### ISSUE THREAD

**Issue by tilmanrossmy** [typelevel/cats#2175]
I have an Abstract Method error in an ammonite script of mine that I can't seem to resolve:
java.lang.AbstractMethodError: cats.implicits$.cats$kernel$instances$BitSetInstances$_setter_$catsKernelStdPartialOrderForBitSet_$eq(Lcats/kernel/PartialOrder;)V
  cats.kernel.instances.BitSetInstances$class.$init$(bitSet.scala:9)
  cats.implicits$.<init>(implicits.scala:3)
  cats.implicits$.<clinit>(implicits.scala)
  fs2.io.JavaInputOutputStream$.readInputStreamGeneric(JavaInputOutputStream.scala:39)
  fs2.io.package$.readInputStream(io.scala:22)
  fs2.io.package$.stdin(io.scala:119)

So whats missing? An eq Instance for PartialOrder?

**Comment by LukaJCB** [comment]
I think you're running into binary compatability issues, you should check that you have the latest versions of all your libraries.

**Comment by ceedubs** [comment]
I agree with @LukaJCB -- make sure that your library and all of its dependencies are on the same version of cats. You may find a tool like [sbt-dependency-graph](https://github.com/jrudolph/sbt-dependency-graph) useful for this.

Since this thread has gone silent for a little while, I'm going to go ahead and close it out.
