### ISSUE TITLE
Add .isEvaluated to Eval

### ISSUE THREAD

**Issue by n3ziniuka5** [typelevel/cats#2236]
This is a feature request to add `.isEvaluated: Boolean` to `Eval`.

Another possibiltiy would be add `.toOption: Option[A]`. The result of that would be `None` if it wasn't evaluated.

My usecase is that I have a `Free` algebra that composes other algebras that depend on various resources (httpClient, database, etc.). To be able to compose those algebras freely I have a single `Deps` object with all of dependencies that may be needed:
```scala
case class Deps(
  httpClient: ...,
  dbConnection: ...
)

type Target[A] = Kleisli[IO, Deps, A]
```

The problem with that approach is that I may not need all of the dependencies for a certain program, so I could wrap them in `Eval.later` and that would solve it. However, I then have a problem that after I run the program, I need to close all the resources in `Deps`, but for that I need to know what resources have been evaluated. Simply doing `httpClient.value.close()` may create the http client unnecessarily.

**Comment by johnynek** [comment]
I don't think we want to do this. As cats-effect has spun up we have generally regarded the idea that Eval can do effect capture as a bad thing.

See two recent PRs:
exec alias for eval
https://github.com/typelevel/cats-effect/pull/178

resource, which seems like what you want:
https://github.com/typelevel/cats-effect/pull/188

the problem is, the type of Eval implies it is safe, but only maybe not stack safe in some recursions, to call .value. We don't expect that to be an observable effect, if that is the case.

By exposing if the value has been evaluated or not, I feel we are moving further in the direction of writing code that depends on whether or not an Eval has run, which I think is the wrong direction.

Perhaps you can investigate Resource or Bracket: 
https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Bracket.scala

to accomplish what you are trying to do. It seems like you want an `MVar[Option[Client]]` or something, but I don't think we have an MVar like type in cats-effect yet.

I would recommend we re-open this discussion on cats effect and discuss solutions there.

**Comment by n3ziniuka5** [comment]
I get your point and understand that something like this makes more sense in cats-effect.

For the time being I just wrote a small class that solves this particular problem for me. I'll be able to move to a cats-provided solution if one becomes available at some point.

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out as a stale issue. The comments propose some alternative solutions that are probably more robust and less likely to cause gotcha bugs for users.
