### ISSUE TITLE
MonadError syntax for OptionT uses incorrect instance

### ISSUE THREAD

**Issue by wedens** [typelevel/cats#2611]
This PR introduced the problem: https://github.com/typelevel/cats/pull/2299

`MonadError[OptionT[F, ?], Unit]` is given higher priority than `MonadError[F, E] => MonadError[OptionT[F, ?], E]`. 

And, of course, syntax for `MonadError` always resolves the first instance making it useless for any `E` other than `Unit`.

**Comment by SystemFw** [comment]
:+1: to changing it back, http4s is affected, since you can't call `handleErrorWith` on `HttpApp` anymore (it's `Kleisli` of `OptionT`), basically for the purpose of using `MonadError` of `Unit`, which is close to a toy instance.

cc @rossabaker @ChristopherDavenport

**Comment by kailuowang** [comment]
+1 to fix this. 
We have two options. 
1, We can simply make the `Unit` instance explicit
2. We can switch the two and use this trick https://github.com/typelevel/cats/pull/2335#L421-L425 to bump the priority of `MonadError[F, E] => MonadError[OptionT[F, ?], E]`, (otherwise they probably will be of the same priority and causing ambiguity issue.)

**Comment by ChristopherDavenport** [comment]
Definitely, 👍  to this being fixed.

**Comment by barambani** [comment]
I'm having a look if that's all right.
