### ISSUE TITLE
if-conditions in for-comprehensions for EitherT

### ISSUE THREAD

**Issue by zy4** [typelevel/cats#2666]
When using an if-condition to filter an OptionT-Stack, one could simply write:

```scala
for {
  b <- OptionT.pure(true)
 data <- OptionT(someFunction)
 if b
 } yield data
```

The same does not work for `EitherT` for which I would have expected the left side in case of false.

**Comment by mpilquist** [comment]
Consider a similar program using `Either[L, R]` instead of `EitherT[F, L, R]` -- it will similarly not work, with an error indicating that `Either` does not have a member named `withFilter`. The reason neither `Either` nor `EitherT` defines `withFilter` is that upon failure, you need to conjure up a value of type `L` to wrap in a `Left` constructor.

E.g., given `x: Either[String, Int]`, what should `x.withFilter(_ => false)` return?

**Comment by zy4** [comment]
Makes sense! I can always do something like `toOption.withFilter.toRight`, I guess.
