### ISSUE TITLE
[SECURITY] Releases are built/executed/released in the context of insecure/untrusted code

### ISSUE THREAD

**Issue by JLLeitschuh** [typelevel/cats#2820]
[CWE-829: Inclusion of Functionality from Untrusted Control Sphere](https://cwe.mitre.org/data/definitions/829.html)
[CWE-494: Download of Code Without Integrity Check](https://cwe.mitre.org/data/definitions/494.html)

The build files indicate that this project is resolving dependencies over HTTP instead of HTTPS. Any of these artifacts could have been MITM to maliciously compromise them and infect the build artifacts that were produced. Additionally, if any of these JARs or other dependencies were compromised, any developers using these could continue to be infected past updating to fix this.

This vulnerability has a CVSS v3.0 Base Score of 8.1/10
https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H

### This isn't just theoretical
POC code has existed since 2014 to maliciously compromise a JAR file inflight.
See:
* https://max.computer/blog/how-to-take-over-the-computer-of-any-java-or-clojure-or-scala-developer/
* https://github.com/mveytsman/dilettante

### MITM Attacks Increasingly Common
See:
* https://serverfault.com/a/153065
* https://security.stackexchange.com/a/12050
* [Comcast continues to inject its own code into websites you visit](https://thenextweb.com/insights/2017/12/11/comcast-continues-to-inject-its-own-code-into-websites-you-visit/#) (over HTTP)

### Source Locations

https://github.com/typelevel/cats/blob/a6723ac847860a8fd5b0e7c89085087c6e6ce7bd/build.sbt#L83

#### Option 1: File for a CVE

A project maintainer for this project should probably file for a CVE number to inform the public about this vulnerability in the build for this project. The goal is to inform the public that there was a potential for published build artifacts to have been maliciously compromised in earlier releases.

If a maintainer on this project works for or is associated with a CNA, please have them file it with them:
[cve.mitre.org/cve/request_id.html](https://cve.mitre.org/cve/request_id.html)

Otherwise, an open source CVE should be filed for here:
[iwantacve.org](https://iwantacve.org/)

#### Option 2: Manually validate the release artifacts

If this project's build is [fully reproducible](https://en.wikipedia.org/wiki/Reproducible_builds). An alternative to filing for a CVE is to go back and build the earlier releases (with the HTTPS patch applied) to confirm the artifacts were not tampered when they were built. This can be done by comparing the hashes of the artifacts built locally with the ones published. If the hashes of all previous artifacts match those that are published, you can safely assume that the releases were not tampered with.

Again, this assumes that the build if fully reproducible and will require significantly more work.

**Comment by JLLeitschuh** [comment]
Related locations:
- https://github.com/typelevel/sbt-catalysts.g8/blob/a74f48bdd0f5ed150c0881b4646a7d5137c84903/build.sbt#L11

**Comment by non** [comment]
I don't think we need this anymore, since kind-projector has been on Maven Central for a long time.

(If there's something else I've published to Bintray recently please let me know and I'll publish to Maven Central.)

**Comment by kailuowang** [comment]
#2821 removing unused resolver was merged. I didn't get a chance to close this yet.

**Comment by JLLeitschuh** [comment]
Hi @non @kailuowang,

What is your plan on the public disclosure aspect?

**Comment by kailuowang** [comment]
@JLLeitschuh sorry I missed that part. I verified that post Cats 1.0, we have not downloaded any dependencies through that bintray repository. (actually it probably dates to much earlier, but I haven't got the time to pinpoint which release)
I will file a CVE to disclose that.

**Comment by non** [comment]
Based on some archeology I did, we stopped using kind-projector 0.6.2 (the version resolved from Bintray) in August 2105: https://github.com/typelevel/cats/commit/8c2333c021

**Comment by kailuowang** [comment]
thanks @non. That  means Cats only released 3 unofficial releases that has the possibility of being compromised.  0.0.0, 0.1.0, and 0.1.1, not sure if we need to disclose those.

**Comment by kailuowang** [comment]
Just checked the only possibly affected cats releases are `0.1.2` and `0.1.1` released July 17 2015, and they were published under a different group id "org.spire-math" when the cats github repo was still under @non's account IIRC. https://search.maven.org/search?q=g:org.spire-math%20AND%20a:cats_2.10&core=gav
@JLLeitschuh I suggest we close this issue.

**Comment by JLLeitschuh** [comment]
Just clarifying, this code was never executed in the context of a release since version 0.1.2? If that's the case, this issue can be closed as fully resolved. Nice work.

**Comment by non** [comment]
@JLLeitschuh that's right. thanks for bringing this to our attention!

**Comment by djspiewak** [comment]
Also worth noting that kind-projector only exists within the compile-time dependency set. Thus any hypothetical attack would involve a MITM attack on a cats developer, causing them to resolve a backdoored version of kind-projector which in turn generates backdoored code. This kind of attack is, technically speaking, an order of magnitude harder to execute than a conventional dependency backdoor due to the compiler indirection (and the complexity of the compiler in question), but still certainly possible. It also presents a very very limited set of targets: really, just the developer who publishes cats releases to Sonatype. Most of the cats developers already take significant precautions to limit the practicality of targeted MITM attacks through their own personal security practices.

We can go a step further though in this archeology and look at exactly *who* published 0.1.2 and 0.1.1, since those are the only releases which could have involved a backdoor, and whoever created the tag is presumably the individual who also built the binaries, and thus would need to be the individual who's personal infrastructure (laptop, home internet/VPN, etc) was compromised.

```
commit c853f5f8c3be173dd929635bdbef7ee7a4c6c905 (tag: v0.1.1)
Author: Erik Osheim <d_m@plastic-idolatry.com>
Date:   3 years, 10 months ago

    Setting version to 0.1.1

commit 535748bd116aea7836e962cd58170caf681e9c18 (tag: v0.1.2)
Author: Erik Osheim <d_m@plastic-idolatry.com>
Date:   3 years, 10 months ago

    Setting version to 0.1.2
```

We can't know for sure unless @non were to do an audit, and even then it's not certain, but honestly Eric's personal security practices are pretty much as trustworthy as it gets, and seeing as these were two minor releases (used by almost no one at the time) and significantly obsolete, coupled with the difficulty of executing any such attack *through* kind-projector from a purely technical standpoint, makes me think that we can all feel very very much at ease on this point.

**Comment by JLLeitschuh** [comment]
The risk in this kind of attack is mostly related to the following chain of events:
1. Download a compromised JAR
2. Run tests before a release with that compromised JAR's code now executing on your machine
3. Malicious JAR being executed as a part of the tests turns around and backdoors your JAR before being uploaded to Sonatype.

Since it's from 3 years and 10 days ago, and it's only two releases, and it hasn't been used since, you're probably good.

**Comment by kailuowang** [comment]
Great I am closing this. Thanks @JLLeitschuh for raising the issue. Thank you @non and @djspiewak for investigating.
