### ISSUE TITLE
FunctorFilter instance for IO?

### ISSUE THREAD

**Issue by ShahOdin** [typelevel/cats#3018]
Is there any reason why we don't have the following `FunctorFilter` implementation for `IO`?

```import cats.effect.IO
import cats.implicits._
import cats.FunctorFilter
import cats.Functor

implicit object IOFunctorFilter extends FunctorFilter[IO] {
  def functor: Functor[IO] = IO.ioEffect
  override def mapFilter[A, B](fa: IO[A])(f: A => Option[B]) = fa.flatMap(
    a => IO.fromEither[B](
      Either.fromOption(f(a), new Exception("None"))
    )
  )
}
```

**Comment by djspiewak** [comment]
Better to ask this question on the https://github.com/typelevel/cats-effect project directly, rather than here. But the short answer is that there isn't an unambiguous zero. You used `new Exception("None")`, but I might have *expected* `new Exception("zero")`, or `new Throwable`, or any number of other things.
