### ISSUE TITLE
Why no FlatMap instance for NonEmptySet?

### ISSUE THREAD

**Issue by ShahOdin** [typelevel/cats#3093]
NonEmptyList has instances for `Apply`, `FlatMap` etc whereas NonEmptySet doesn't have them. Is there any reasons for it?

Currently This is how I do my flatMaps with `NonEmptySet` instances. 

    object demo extends App {
      import cats.data._
    
      import cats.instances.all._
    
      val foo = NonEmptySet.of(1, 2, 3)
      val bar = NonEmptySet.of(10, 20)
    
      val x: SortedSet[Int] = for {
        f <- foo.toSortedSet
        b <- bar.toSortedSet
      } yield f * b
    
      val y: NonEmptySet[Int] = NonEmptySet.fromSetUnsafe(x)
      println(y)
    }

Which is not great. Is there any reasons why we can't we have a FlatMap instance for `NonEmptySet`?

**Comment by larsrh** [comment]
The problem is more fundamental: there isn't even a `Functor` instance on `SortedSet`. The full signature of `map` from the stdlib looks as follows:

```scala
def map[B](f: (A) => B)(implicit ev: Ordering[B]): SortedSet[B]
```

Mapping to a different type `B` requires an `Ordering[B]`, because it may change the structure of the underlying tree. Hence, `map`, `flatMap`, and some other operations too need to know about the target ordering.

Conversely, the `map` function as defined by Cats' Functor does not offer the possibility to specify the `Ordering`. Hence, the operation cannot be implemented.

What we _could_ in principle provide are "bare" `map` and `flatMap` methods without implementing the type classes. This is why I'm letting this issue open.

More details on the theoretical problem behind this (applies to Cats too): https://typelevel.org/blog/2014/06/22/mapping-sets.html
