### ISSUE TITLE
A new dedicated Cats ecosystem page(s)

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#3121]
The cats ecosystem has grown tremendously in the past couple of years. 
We should build a page to help people better navigate the ecosystem. 
I think we can start with one page with 2 sections: 
1. a complete list of ecosystem libraries, we can start with a consolidated list from [here](https://github.com/typelevel/cats/blob/master/README.md#general-purpose-libraries-to-support-pure-functional-programming), [here](https://github.com/typelevel/cats-effect#libraries), [here](https://github.com/functional-streams-for-scala/fs2#projects-using-fs2) and other existing lists. 
2. a recipe list of `how to do XXXXX (in cats ecosystem)`, for example,
Q:  "how do create a command line application? " 
A:  follow this example that uses `decline` and IOApp from `Cats.effect`

**Comment by benkio** [comment]
Hi there,
I'm interested in picking up this one since is a first issue + not a high priority one.
Right now, I cannot compile the microsite because of #3599, but I think I can start anyway.
I have a couple of questions:
- Where do you think is the right place for the page on the site?
- Can we have a quick, first, groom about the content of the list at point 2? 
thank you :pray:

**Comment by kailuowang** [comment]
Thanks so much!
I am thinking, for the recipe list, we can start with a couple of examples as a good start for the community to contribute more (which we might be able to solicit on SNN regularly). 
Some other quick examples I can think of (of course they might be expanded a bit). 

* How to retry an effect? Take a look at Cats-retry
* How to properly do logging? Take a look at log4cats
* How to automatically poll data from source into memory? take a look at Mau

@ChristopherDavenport probably has more. ;)

**Comment by benkio** [comment]
Additional question :sweat_smile: , for the libraries list:

Do we want to unify all the projects and libraries using `cats` in a single place, and then go on the other pages and just put a link there, like the links you inserted above, or do the other way around (putting links to the other lists in this new page)? 

I'm Asking because I think we should avoid duplication

**Comment by kailuowang** [comment]
IMO I wouldn't worry too much about the duplication across projects. A central place is useful searching libs in the ecosystem while each project might have their own reason to have a libraries list and they can decide if they want to link to the central one.

**Comment by ChristopherDavenport** [comment]
Here is a gist I wrote a little bit ago with my libraries available. If anyone reminds me I can check and add more when I inevitably end up creating more.

https://gist.github.com/ChristopherDavenport/5b900d471922b4da5de7a3dc51edd8d8

**Comment by benkio** [comment]
Great!
I will check that out ASAP to see if I miss some.
At the moment I'm using gists as well while waiting for the doc to be migrated 😉

**Comment by benkio** [comment]
I share with you the screenshot of the first version of the page. Any feedback is appreciated.
I have just a couple of concerns:
 - I feel we should wrap the head around the _How to_ section since right now it only has the Q/As @kailuowang suggested above.
 - At the moment I created a standalone page that appears into the menu as well. Let me know if you want to put that in an existing menu item or whatever.

![image](https://user-images.githubusercontent.com/4698396/92997372-b433e780-f50a-11ea-9598-69a6fa1033b7.png)

Thanks
