### ISSUE TITLE
Incorrect behaviour of EitherT in for-comprehension

### ISSUE THREAD

**Issue by MarkusA380** [typelevel/cats#3275]
Here's a [minimal code example](https://scalafiddle.io/sf/rVtGyhP/0):

```
import cats._
import cats.data._
import cats.implicits._
import cats.syntax._
import scala.concurrent.Future

import scala.concurrent.ExecutionContext.Implicits.global

def getById[A, B](id: String): Future[Either[A, B]] = ???
def update[B](b: B): Future[B] = ???
def changeOldData[A, B](old: B): B = ???

def foo[A, B](id: String) = {
  
   val value: Future[Either[A, B]] = getById(id)
   val value2: EitherT[Future, A, B] = EitherT.apply(value)
   
   for {
      oldResult <- value2
      newResult <- EitherT.right(update(changeOldData(oldResult)))
   } yield newResult
  }.value
```

Compilation leads to this error message (here in ScalaFiddle):

```
ScalaFiddle.scala:21: error: type mismatch;
 found   : scala.this.Function1[B&0,data.this.EitherT[concurrent.this.Future,scala.this.Nothing,B&0]]
 required: scala.this.Function1[B&0,data.this.EitherT[concurrent.this.Future,A&0,B&0]]
        oldResult <- value2
```

This seems to be incorrect behaviour as it is closely comparable to the [documentation](https://typelevel.org/cats/datatypes/eithert.html#eithert-1).

**Comment by djspiewak** [comment]
Unfortunately, `EitherT` is not covariant in its `A` or `B` parameters, meaning that the type of the expression to the right of `newResult` (which is `EitherT[Future, Nothing, B]`) is actually incompatible with the type of `value2` (which is `EitherT[Future, A, B]`). The documentation avoids this problem by having fully defined types in each case, while you're asking the compiler to do some extra inference legwork by using `EitherT.right`.

To be clear, there's nothing wrong with what you're *trying* to do here, it's just not compiling because of the lack of variance.

The solution is to add the type parameter to the `right` invocation:

```scala
   for {
      oldResult <- value2
      newResult <- EitherT.right[A](update(changeOldData(oldResult)))
   } yield newResult
```

And now it should work! `right` (and `left`) use the "partially-applied type parameters" pattern, which, among other things, usually *requires* that the type parameter is fully specified rather than left up to the compiler to infer.
