### ISSUE TITLE
TraverseFilter won't short circuit 

### ISSUE THREAD

**Issue by gagandeepkalra** [typelevel/cats#3327]
`TraverseFilter` won't short-circuit for `Set`, `LazyList`, `Vector` and `Queue`. For other instances, it's done correctly.

e.g.

```
import cats.implicits._
import scala.collection.immutable.Queue

scala> val f: Int => Either[String, Option[Int]] = i => {
  print(s"$i ")
  if (i > 0) Right(Some(i)) else Left("not positive")
}

scala> List(2, 1, 0, -1).traverseFilter(f)
2 1 0 res0: Either[String,List[Int]] = Left(not positive)

scala> Vector(2, 1, 0, -1).traverseFilter(f)
-1 0 1 2 res1: Either[String,scala.collection.immutable.Vector[Int]] = Left(not positive)

scala> Queue(2, 1, 0, -1).traverseFilter(f)
-1 0 1 2 res2: Either[String,scala.collection.immutable.Queue[Int]] = Left(not positive)

```

[Conversation](https://github.com/typelevel/cats/pull/3292#discussion_r377590934) for reference.

**Comment by travisbrown** [comment]
Thanks for opening this, @gagandeepkalra! I'm planning to take a closer look at this in the next few days.

**Comment by travisbrown** [comment]
One thing that's worth noting here: the bug doesn't extend to laziness of effect evaluation, in which respect (as far as I've checked) all of these instances are correct. The issue is that for strict types with a failed state (like `Either`) the function is applied in cases where it doesn't need to be, and where it isn't for e.g. the `List` instance.
