### ISSUE TITLE
Weird new `Could not find implicit`if comonad is defined

### ISSUE THREAD

**Issue by adrian-salajan** [typelevel/cats#3494]
I encountered a very strange issue while writing tests using cats-laws.
After defining an implicit instance for comonad, my tests using cat-laws does not compile anymore, failing with:

```
Error:(72, 81) could not find implicit value for parameter iso: cats.laws.discipline.SemigroupalTests.Isomorphisms[[A]dimages.Image[A]]
  checkAll("Applicative laws", ApplicativeTests(Image.imApplicative).applicative[Int, Int, String])
Error:(75, 57) could not find implicit value for parameter iso: cats.laws.discipline.SemigroupalTests.Isomorphisms[[A]dimages.Image[A]]
  checkAll("Monad laws", MonadTests(Image.imMonad).monad[Int, Int, String])
```

If i just make the comonad instance private, and rebuilt, the problem is fixed.
I'm not sure if this is a cats or SBT issue.

How to replicate:
checkout branch weirdBug: https://github.com/adrian-salajan/dimages/tree/weirdBug/

make private or public the `imComonad` instance defined in 
https://github.com/adrian-salajan/dimages/blob/weirdBug/src/main/scala/dimages/Image.scala

recompile/run tests
https://github.com/adrian-salajan/dimages/blob/weirdBug/src/test/scala/dimages/ColorTest.scala

**Comment by djspiewak** [comment]
You need to merge together your functor, applicative, monad, and comonad definitions all into one. Something like this:

```scala
// note that the functor and applicative instnaces were redundant
implicit def instances: Monad[Image] with Comonad[Image] = ???
```

The reason being that `Monad` and `Comonad` both inherit from `Invariant`, which in turn implies `Isomorphisms`, which is why you're getting the error. As a general rule, *any* instances you wish to define for a datatype which are within the functor hierarchy (i.e. anything that derives from `Invariant`) must be merged together in this fashion, otherwise you will get ambiguities.
