### ISSUE TITLE
Either's `ApplicativeError.ifA` sometimes return wrong branch

### ISSUE THREAD

**Issue by seigert** [typelevel/cats#3583]
I'm not even sure this is a right repo for this issue and looking at code I could not determine what is the could cause this, but...

The following ammonite test script fails first test:

```scala
import $plugin.$ivy.`org.typelevel::kind-projector:0.10.3`
import $ivy.{
  `org.typelevel::cats-core:2.1.1`,
  `org.scalatest::scalatest:3.2.2`,
  `org.scalatestplus::scalacheck-1-14:3.2.2.0`
}

import cats.{ ApplicativeError, MonadError }
import cats.implicits._
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks

class EitherCatsSpec extends AnyFlatSpec with Matchers with ScalaCheckDrivenPropertyChecks {

  "ApplicativeError[Either[String, *], String].ifA" should "return correct branch" in {
    forAll { b: Boolean =>
      val A = ApplicativeError[Either[String, *], String]
      val e = A.ifA(Right(b))(Right(1), Left("left"))

      if (b) e.shouldEqual(Right(1))
      else e.shouldEqual(Left("left"))
    }
  }

  "MonadError[Either[String, *], String].ifM" should "pass to correct branch" in {
    forAll { b: Boolean =>
      val M = MonadError[Either[String, *], String]
      val e = M.ifM(Right(b))(Right(1), Left("left"))

      if (b) e.shouldEqual(Right(1))
      else e.shouldEqual(Left("left"))
    }
  }

}

(new EitherCatsSpec).execute()
```

Versions: AdoptOpenJdk 8u265 & OpenJDK 11.0.2, Scala 2.13.3, kind-projector 0.10.3, cats 2.1.1, scalatest 3.2.2, scalatestplus-scalacheck-1-14 3.2.2.0, scalacheck 1.14.3

---
Edit: add Ammonite script to reproduce.

**Comment by fthomas** [comment]
`A.ifA(Right(b))(Right(1), Left("left"))` always returns `Left("left")` independent of the value of `b` because the [implementation of `ifA`](https://github.com/typelevel/cats/blob/7c07f71e73e691469d07e79044674c325c7daaa7/core/src/main/scala/cats/Apply.scala#L256-L258) always combines of the effects of the condition and both branches. Since it is defined on `Apply`, there is no way to not take the effects of both branches into account. This can only be done with `flatMap` which is used in the implementation of `ifM`. `ifA` and `ifM` are deliberately not the same. 

Note also the Scaladoc of `ifA`:

> An `if-then-else` lifted into the `F` context.
> This function combines the effects of the `fcond` condition and of the two branches,
> in the order in which they are given.

**Comment by seigert** [comment]
I'm not sure I follow: what the point of `ifA` if it only ever returns `else` branch? Then it would be equivalent to `map(product(fcond, product(ifTrue, ifFalse)){ case (_, _, false) => false }`

`Apply.ifA` implementation clearly includes auxiliary function [`ite`](https://github.com/typelevel/cats/blob/7c07f71e73e691469d07e79044674c325c7daaa7/core/src/main/scala/cats/Apply.scala#L257) which in our case should became `if (b) Right(1) else Left("left")`.

Also, `ifA` scaladoc states that:
```
* scala> val b1: Option[Boolean] = Some(true)
* scala> val asInt1: Option[Int] = Apply[Option].ifA(b1)(Some(1), Some(0))
* scala> asInt1.get
* res0: Int = 1
```

**Comment by fthomas** [comment]
> what the point of ifA if it only ever returns else branch?

It returns the else branch because that is a `Left`. If the condition or any of the branches is a `Left` the whole expression evaluates to a `Left`. Only if all three are `Right`s you'll get the result of `ite`.

> Apply.ifA implementation clearly includes auxiliary function ite which in our case should became if (b) Right(1) else Left("left").

`ite` has type `def ite(b: Boolean)(ifTrue: A, ifFalse: A): A`. `A` is `Int` in your case, so it can't be `if (b) Right(1) else Left("left")`. `ite` can only be called if there are two `Int` values for both branches but since your else branch is a `Left` that function is never used.

**Comment by seigert** [comment]
Yeah, I think I understand: `ifA` defined through `ap2` and `ap2` defined via `map` and `product` and both of them only ever continue evaluation in case of `Right`'s and short circuit in case of `Left`. And as soon as we introduced already evaluated `Left("left")` to `ifA`, `product(fa, product(fb, ff))` will became `Left("left")` an so on.

Thanks!
