### ISSUE TITLE
Future Apply to regain parallelism 

### ISSUE THREAD

**Issue by SimY4** [typelevel/cats#3587]
I noticed that because Monad instance for scala Future is not defining its own apply method (ap, ap2, map2, product, productL, productR), their implementation is coming from `FlatMap` typeclass where they are defined in terms of flatMap.

Which in turn cause that `Apply` composition of Futures actually has sequential semantics rather than parallel as you would expect.

We should probably override and reimplement apply method on Future using provided Future's zip and zipWith methods to gain parallelism back.

**Comment by joroKr21** [comment]
Actually once a future is created it is already running, so `mapN` and `sequence` are parallel, but `traverse` is sequential.

**Comment by SimY4** [comment]
My bad, I can see that Future itself internally is just doing flatMap on them.

**Comment by djspiewak** [comment]
> I noticed that because Monad instance for scala Future is not defining its own apply method (ap, ap2, map2, product, productL, productR), their implementation is coming from FlatMap typeclass where they are defined in terms of flatMap.

This is an interesting discussion, but just to be clear, there are *two* possible `Apply`s for `Future`: one defined in terms of `flatMap`, and another defined in terms of `zip`. However, *by law*, `ap` needs to be defined in terms of `flatMap`, otherwise you could change your program significantly by refactoring. For example:

```scala
fa >> fb
fa *> fb
```

These should be the same program, right? Except one of them is `flatMap` while the other is `ap`, and if `Apply` is inconsistent with `flatMap`, you could make this entirely innocuous change and suddenly see significant semantic shifts.

The cats solution to this problem (of two `Apply`s), in general, is `Parallel`. The idea behind `Parallel` is it forms a mechanism to get an *alternative* `Applicative` for a particular `F[_]`. In the case of `Future`, an alternative `Applicative` would be one which uses `zip` under the surface, rather than delegating to `flatMap`, and thus gives you parallel semantics for independent composition.

**Comment by joroKr21** [comment]
But this breaks down when it comes to `Future` because `fa >> fb` and `fa *> fb` could in practice make the difference between sequential and parallel (depending on whether `fa` and `fb` are vals or defs).

**Comment by djspiewak** [comment]
> But this breaks down when it comes to Future because fa >> fb and fa *> fb could in practice make the difference between sequential and parallel (depending on whether fa and fb are vals or defs).

Right, `Future` is basically just a terribly confusing type. :-) It isn't referentially transparent in conventional usage, so you can poke holes in pretty much every possibly "safe" refactoring (up to and including functor identity). This is kind of a fundamental problem with `Future` though, but I think it's important not to make it *even worse*. :-)

On a prior art note… Scalaz used to define `ap` for `Future` using `zip` before ultimately ripping it out in response to several years of confused bug reports.
