### ISSUE TITLE
Why is a List not a functor?

### ISSUE THREAD

**Issue by SarpongAbasimi** [typelevel/cats#3725]
I started reading the book scala with cats and it states that 
`Option`, `List`, and `Either` are all functors.

<img width="563" alt="Screen Shot 2020-12-25 at 14 14 40" src="https://user-images.githubusercontent.com/37377831/103136814-a110e600-46bb-11eb-97dd-b22560497147.png">

I created a simple method

```
  def foo(a: Functor[Int]) : Functor[Int] = {
    a
  }
 foo(List(1,2,3))
```
but this does not work because `List(1,2,3)` is not a functor
<img width="395" alt="Screen Shot 2020-12-25 at 14 17 23" src="https://user-images.githubusercontent.com/37377831/103136887-2a281d00-46bc-11eb-9ffc-516db043b714.png">

so please what exactly is a Functor? What do I have to pass to the function to make is compile?

I have the same issue with 
- Applicatives
- Monads 

Please have some patience with me, I just want to understand these concepts and have a mental model or visual representation of what these are.

When someone says `create a list, sequence or an option of something`, I know straight away that a `list` is `List()` a sequence is `Seq()` and option is `Some()` but I do not have the model for `Functors`, `Monads` and `Applicatives`.

Please if You can explain this using simple words, I will be grateful.
thank you

**Comment by rossabaker** [comment]
A `List` is a `Seq` because there is a _subtype_ relationship: `sealed abstract class List[+A] extends AbstractSeq[A]`.  You can write code that is _polymorphic_ for `Seq`s -- in other words, you can give it a `List` or a `Vector`.   But that polymorphism extends only to types that _extend_ `Seq`.  That means that it only works for types that know about and are compiled against `Seq`.

By contrast `Functor`, `Monad`, and `Applicative` are examples of _type classes_.  `List` doesn't extend `Functor`, but there is an implicit _instance_ of `Functor[List]`:

```scala
@ import cats._ 
import cats._

@ implicitly[Functor[List]] 
res2: Functor[List] = cats.instances.ListInstances$$anon$1@3f362135
```

`List`, which comes from Scala, doesn't know anything about `Functor`, which comes from cats.  But with the type class approach, we can express that `List` acts like a `Functor`.  This is called _ad hoc polymorphism_.  So you would call it something like this:

```scala
@ def foo[F[_]](a: F[Int])(implicit F: Functor[F]): F[Int] = F.map(a)(_ + 1) 
defined function foo

@ foo(List(1, 2, 3)) 
res16: List[Int] = List(2, 3, 4)
```

* The `F[_]` is a type parameter for types of a _kind_ that take another type parameter.  Like `List[A]`, but unlike `String`.  
* The `implicit F: Functor[F]` summons the functor instance for `F`.  As shown above, there is an implicit `Functor[List]` instance, so we can call `foo` with a `List`.
* The `implicit F` gives us access to the operations of `F`.  In this case, `map`, which is the essence of a functor.

Lots more things than `Seq`s have a functor instance.  Try it with `Option` and `Future`.  As you get more advanced, you'll create your own functor types, and can provide an implicit instance of your own, and you can call `foo` with it!

That's not a complete explanation, but hopefully it sheds some light.  I imagine the book will give a more thorough explanation, and the words I put in italics are good keywords for more reading.

**Comment by SarpongAbasimi** [comment]
Thank you @rossabaker I think I understand it much better now. 
so in short
`List`, `Option`, `Either` are not `Functors` per say, they can act as `Functors` when we do have their `Functor instances` in `scope`.

Which also means that the method below is actually wrong because we do not have a `type class` instance for a `Functor[Int]`.
```
  def foo(a: Functor[Int]) : Functor[Int] = {
    a
  }
```
