### ISSUE TITLE
Parallel for EitherT and IorT is probably over constrained

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats#3776]
For more discussion on this, see https://github.com/typelevel/cats-effect/issues/1645. The short form is that EitherT and IorT require a Semigroup/Monoid on their error type to derive a Parallel. This gives rise to semantics which are inconsistent with more fundamental derivations of the Parallel type.

At the present moment, it is undecided how best to resolve this, but one possibility is to change the derivations in Cats itself, which is what this issue is now tracking.

**Comment by LukaJCB** [comment]
Urgh this is totally my bad. It's because the semantics are taken from `Either`, which through `Parallel` turns into `Validated` and therefore requires the monoid constraint. Seemed like a good idea at the time...

**Comment by Baccata** [comment]
@djspiewak says : 

> inconsistent with more fundamental derivations of the Parallel type.

@djspiewak, how are the derivations you're thinking of more fundamental ? The layering of semantics via a monad stack is interesting because the composition of layers respect the semantics of each layer individually. I'd even go as far as saying that this quality should be a *fundamental law* to the very concept of monad transformer : 

* given `M` a Monad and `MT[*[_], *]` its transformer counterpart, `M <-> M[Id, *]`

> Urgh this is totally my bad. It's because the semantics are taken from Either, which through Parallel turns into Validated and therefore requires the monoid constraint. Seemed like a good idea at the time...

@LukaJCB, I totally agree with these semantics, as a matter of fact, I'm currently facing an *actual* use-case where `EitherT[Writer[L, *], NonEmptyList[E], *]` is a perfect fit, *because* the `EitherT`'s `Parallel` reflects the behaviour of `Either`'s Parallel, and I can use it that to aggregate errors via a parallel composition. 

Changing the behaviour of `Parallel` for `EitherT` would completely break this very valid use of it, and I'd be left having to create my own `Either`, which would utterly suck for a great number of reasons .

**Comment by Baccata** [comment]
Alright, so I take it there are four cases to this problem : 

| F[_] \ E    | Semigroupal                                                                              | Non-semigroupal                                                          |
|-------------|------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|
| Parallel    | 1.1 EitherT's parallel respects F's parallelism and allows for combining errors          | 1.2 EitherT's parallel respects F's parallelism but never combines errors |
| NonParallel | 2.1 EitherT's parallelism allows for combining errors but always composes F sequentially | 2.2 no instance                                                          |

* Currently, cats-core has instances for 1.1 and 1.2
* **2.1 is missing** and that's a problem that I think @djspiewak is pointing out
* Daniel's [changes](https://github.com/typelevel/cats-effect/issues/1645) are removing 1.1 in favour of 2.1 
* I think 1.1, 1.2 and 2.1 are all valid cases for `Parallel` instances on `EitherT` (and `IorT` obviously), and that 1.1 should retain highest priority during resolution.

**Comment by Baccata** [comment]
Alright so after a chat with @djspiewak, here's my current state of thoughts (echoing https://github.com/typelevel/cats/pull/3777#issuecomment-775317341): 

1. there is no intuition about these things that is inherently correct because the concept of MonadTransformer doesn't come with Laws, and that Parallel itself (despite being a lawful construct) is rather ad-hoc : its meaning is not as well outlined as other typeclasses.
2. therefore I think that neither Daniel's point of view nor mine are inherently correct on this issue. 
3. in the grand scheme of things, a lot of people have an intuition that `Concurrent` and `Parallel` are one and the same thing, which tends to trip up a lot of people. Even if that equivalence is clearly wrong, having `Parallel` implied easily by `Concurrent` is very desirable in the ecosystem. 
4. I will not admit that my own intuition about the current Parallel instance for EitherT is invalid, but I'll admit that it makes it harder for point 3 to be delivered. 

Therefore I'd be satisfied if there was a way to regain the current semantics. I think I'd favour a non-orphaned instance, but if there was an orphan instance that could be accessed easily without colliding with the `Concurrent => Parallel` one, I'd personally be okay.
