### ISSUE TITLE
Add EitherThrow type alias

### ISSUE THREAD

**Issue by geirolz** [typelevel/cats#3953]
It would be useful to have a type alias like this in Cats, following the same approach of `MonadError` and `ApplicativeError`
```scala
type EitherThrow[+T] = Either[Throwable, T]
```

**Comment by rossabaker** [comment]
Is it just to be more concise?  I've done a lot of aliasing of concrete types, and come to regret most of them.

**Comment by geirolz** [comment]
@rossabaker Yes, just to have a more readable code. Currently, there are `MonadThrow` and `ApplicativeThrow` type aliases so I wonder if `EitherThrow` can be useful.  

I did the same, at some time you have to read the alias every time to understand the code...but in this case, I think can but clear, often `Either` is used with `Throwable` on the left side

**Comment by rossabaker** [comment]
I agree these aliases can make the code a bit easier to read, but a tradeoff is that compiler errors get more difficult.  The code says one thing, but the errors say another, and I've seen beginners struggle with this.

I think `MonadThrow` and `ApplicativeError` carry a bit more weight.  Being able to express constraints with kind `F[_]` instead of `F[_, _]` alleviates the cognitive burden of kind projection, syntax that has evolved from lambdas to earlier versions of kind projector to today.  I think more about kinds when doing typeclass programming, where having one parameter is a sweet spot.  I think the advantages are far less for concrete data types, and tend to avoid them unless the underlying type is an unholy mess that's hard to discuss.  And even then, maybe the problem is the underlying type.

**Comment by geirolz** [comment]
Yea, you're right. Type classes have more benefits with aliases than concrete types, having one single parameter often helps(context-bound without a wild card for example). 

Now, I'm not sure that this alias should be integrated with cats. Maybe it's not totally wrong but, as you said, using aliases you have more difficult errors. Since we don't have a characters tax maybe is better to avoid it

**Comment by geirolz** [comment]
Let's close this, is better to avoid this change
