### ISSUE TITLE
Upgrade default `scalaVersion` to 2.13

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats#4229]
Currently the default `scalaVersion` in the build is Scala 2.12.
https://github.com/typelevel/cats/blob/7ad08aa1a8ef116c4d3ff95461c7038c7a59eb81/build.sbt#L24

This is because the mdocs for the website currently do not compile on Scala 2.13. This should be investigated and fixed.

~Besides other good reasons to get onto 2.13, this issue became more pressing as of the imminent Scala 2.12.16. Unfortunately it seems that Metals may have degraded support for kind-projector in Scala 2.12.16. See:~
- ~https://github.com/scala/bug/issues/12607~
- ~https://github.com/scalameta/metals/pull/4010#discussion_r893442367~

Update: Metals was testing against legacy kind-projector syntax, seems this is ok after all.

Note: we could de-couple the `scalaVersion` used for building docs from the default `scalaVersion` used for the rest of the build, but I'd rather take this opportunity to force us to fix the docs.

**Comment by tgodzik** [comment]
>  Unfortunately it seems that Metals may have degraded support for kind-projector in Scala 2.12.16. See:

It seems that this actually happened somewhere after `0.10.3` and also this got highlighted by Scala 2.12.16. I am not sure what is happening. I am not a macro expert but does kind projector transform the trees to something with existential types? Or maybe it's only an issue in out snippet? It's available in https://github.com/scalameta/metals/blob/main/tests/cross/src/test/scala/tests/pc/MacroCompletionSuite.scala#L167

I think that maybe existential types were never well supported in the presentation compiler and that's why this happening?
