### ISSUE TITLE
(very breaking) change in Future instances?

### ISSUE THREAD

**Issue by yurique** [typelevel/cats#4617]
The following code works differently with cats `2.10.0` and cats `2.11.0+`

```scala
def test(i: Int): Future[Unit] = 
  for {
    _ <- Future { println(s"start $i") } 
    _ <- futureSleep(100.millis) // just to avoid any timing issues, reproduces without it as well
    _ <- Future { println(s"end $i") } 
  } yield ()

List(1, 2, 3).traverse(test)
```

With `2.10.0` it prints (https://scastie.scala-lang.org/RYQcjXExR4m0NQQBHVo25w):
```
start 1
end 1
start 2
end 2
start 3
end 3
```

With `2.11.0+` (https://scastie.scala-lang.org/F21nFlI1Tl2bYm271o50ng):
```
start 1
start 2
start 3
end 1
end 2
end 3
```

**Comment by mpilquist** [comment]
Note the 2.11 behavior matches that of `Future.traverse` (https://scastie.scala-lang.org/aU1EoSBnQu2rbWiXtEbcsQ)

**Comment by yurique** [comment]
Right, it does 🤔. 
But it doesn't match the `traverse` with IO: https://scastie.scala-lang.org/1JfGkbQOSTicrUyPaERQhw

Regardless, it still looks like a very breaking change.

**Comment by armanbilge** [comment]
> it still looks like a very breaking change

looks like, but is not. See previous discussion:
- https://github.com/typelevel/cats/issues/4176
- https://github.com/typelevel/cats/pull/4230

**Comment by johnynek** [comment]
The problem is Future, and hence this function `test: Int => Future[Unit]` is not pure.

When you call test a side effect immediately starts. That is not true of the IO version. When you are working with Future you are working with an impure type and we don't limit the traverse implementation of data types to try to work that.

A PR was created where a lot of energy was spent to optimize traverse implementations: https://github.com/typelevel/cats/pull/4498 -- I think it is very likely the change you are seeing is due to that.

I guess what is happening is that since Future has a StackSafeMonad, it is traversing directly (which is what the standard library does), but that is triggering the side-effects in a different order.

**Comment by yurique** [comment]
> looks like, but is not

It depends on how you look at it (or how much code you need to fix) 😆.

--- 

Thanks for chiming in, everyone! I'll close this one and will go hunting down my traverses :)
