### ISSUE TITLE
alleycats - `Extract[F[_]]` the only way to get the syntax is the deprecated one

### ISSUE THREAD

**Issue by arturaz** [typelevel/cats#4642]
![image](https://github.com/user-attachments/assets/349655d3-b81c-487c-92c4-484711ffaa02)

**Comment by aluscent** [comment]
How can I resolve this issue? I like to contribute; would please provide more details? Should something be added to the documentation?

**Comment by satorg** [comment]
@aluscent , thank you for offering your help!

If you'd like to, feel free to file a PR. I'd suggest to follow the same code pattern that is used for syntaxes for `Empty` and `Foldable` type classes in `alleycats.syntax`: create `ExtractSyntax` with corresponding methods, then a new `object extact extends ExtractSyntax`. Also make sure that `alleycats.syntax.all` inherits to `ExtractSyntax` as well.

Personally, I'd probably also consider making `trait ExtractSyntax` private to the `alleycats` package, but since neither `EmptySyntax` nor `FoldableSyntax` in there are private, I don't have a strong opinion on that.

Also I believe that some tests that could check the new syntax works as expected would be helpful. But it looks like no one've even bothered writing tests for "alleycats", so it is up to you. But you could be the first one, if you'd like to.

**Comment by aluscent** [comment]
Dear @satorg thank you for your guidance.

I fixed the extract and added `ExtractSyntax` and an object `extract` - just like `empty`. I also didn't make it private according to `EmptySyntax` and `FoldableSyntax`.

Also I want to write test cases for them, but I will need some guidance again. Should I write tests for the whole alleycats-core? Where should I place them - in `alleycats-core/src/test` or the `tests/shared/src`?

**Comment by satorg** [comment]
@aluscent you don't have to write all the test for sure. I can if you'd like, but I'd suggest to arrange all unrelated tests in a separate PR.

Regarding the location question – I'm not sure, to be honest. Cats uses the  separate `tests` module for `cats-core` and `cats-kernel`, but some other modules use their own test directories for that (e.g. `alleycats-laws`).

I'd say it is safe to assume that we can start with `alleycats-core/src/test` for now unless there are objections from other members of the community.

**Comment by aluscent** [comment]
@satorg thanks for the response. I'm working on the tests. I was busy last week and it took so long to work on this issue.
Also, would you please assign this issue to me? Is it ok to do so? I mean policy wise...

**Comment by satorg** [comment]
@aluscent , thank you!
Just in case, here is an example of tests for cats-core syntaxes: [SyntaxSuite](https://github.com/typelevel/cats/blob/main/tests/shared/src/test/scala/cats/tests/SyntaxSuite.scala)
