### ISSUE TITLE
Add previous API versions to website

### ISSUE THREAD

**Issue by ghost** [typelevel/cats#489]
I  [previously discussed](https://gitter.im/non/cats?at=55c8d61d21801cd866ca8f9a) with @travisbrown if previous API versions should be published to the website. The downside was that search engines tag on old versions.

I'm resurrecting this topic based [on a chat](https://gitter.im/scala-js/scala-js-website?at=55def47c4c5de5644ea20821) with @ochrons, as the solution appears to be "just a question of couple of soft-links and a robots.txt"

Given this, I'm +1 for having the previous versions. Any other opinions/votes?

**Comment by ochrons** [comment]
So in practice you would have a directory structure like
```
docs/latest
docs/0.1.0
docs/0.1.1
```
where `docs/latest` is a symbolic link to the latest doc directory

and then have a `robots.txt` at root preventing crawlers from indexing anything but `docs/latest`

**Comment by travisbrown** [comment]
One drawback of that approach for GitHub-hosted project sites specifically is that it will require @non to create and maintain a separate `gh-pages` project in order to place the `robots.txt` file at the root of `non.github.io`.

We take a slightly different approach (in a one-off way) with one particular set of old docs we didn't want to break for Twitter Util, where we use canonical links to the new docs in the old docs. At least in theory this means we continue to get SEO credit for old links without having them indexed. It would be more painful to do this in a non-one-off way, though.

The fact that the standard library, Play, etc. still haven't gotten this right after all these years suggests that there _is_ a maintenance cost, even if it's small, but I'm definitely not opposed if @non and others want to pay it.

**Comment by InTheNow** [comment]
This is the [standard libraries `robots.txt`](http://www.scala-lang.org/robots.txt)

```
User-agent: *
Allow: /
```

I reckon - between all of us - we could better that :wink:

**Comment by travisbrown** [comment]
@InTheNow But that's the annoying thing about situations like this: half the time there's some incredibly elaborate story about why some painful issue hasn't been fixed, and the other half it's just that nobody's ever bothered (let's hope this is a case of the latter).

**Comment by InTheNow** [comment]
@travisbrown LOL :+1:

**Comment by armanbilge** [comment]
This will be fixed as of https://github.com/typelevel/cats/pull/4160. We are now publishing unidoc artifacts to maven which for every version can be browsed at javadoc.io.
