### ISSUE TITLE
Make traverse lazy

### ISSUE THREAD

**Issue by julien-truffaut** [typelevel/cats#513]
I believe we can make `traverse` lazy by using thunk or `Eval` in `Applicative.map2` (please correct me if I am wrong)

```scala
def validate(i: Int): Option[Int] = if(i < 5) Some(i) else None

List(1,2,6,8).traverse(validate) // should not evaluate validate(8)
```

**Comment by ceedubs** [comment]
Yes, I believe this is the case, and I would vote :+1: for this happening. The question is where exactly it would need to go, since `map2` is defined in terms of `ap` and `map`. I think in the current state of things, it would need to go in `ap`. @non how does this relate to the monoidal work you've been doing?

**Comment by ceedubs** [comment]
I think that now that `Cartesian` is in place, we should revisit this.

**Comment by ceedubs** [comment]
I'm working on this.

**Comment by ceedubs** [comment]
I have a good start on this in a local branch, but this week got busy. I'm hoping to submit a PR next week.
