### ISSUE TITLE
BindRec

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#616]
https://github.com/scalaz/scalaz/pull/1035
http://functorial.com/stack-safety-for-free/index.pdf

**Comment by paf31** [comment]
:+1: Yes please. This enables a uniform approach to safely running free monads and free monad transformers in monads with a `BindRec` instance (`StateT`, `WriterT`, `ReaderT`, `IO`, etc.)

**Comment by ceedubs** [comment]
Very cool to see the author of the paper weighing in here :). Thank you @paf31.

I just read the paper and am excited about this. The rest of the year is very busy for me with traveling. If nobody else has picked it up before then, there is a chance that I might get to this in mid-December, otherwise I can pick it up in January.

**Comment by TomasMikula** [comment]
I assume the `cats` name for `BindRec` will be `FlatMapRec`.

Two more questions to answer:

1. Also add `MonadRec`, or just `FlatMapRec`?  
  (`scalaz` added only `BindRec` and where `MonadRec[M]` is needed, it requires both `BindRec[M]` and `Applicative[M]` instead.)
2. The signature of `tailRecM` transcribed directly from the paper is

  ```scala
  trait FlatMapRec[F[_]] extends FlatMap[F] {
    def tailRecM[A, B](f: A => F[A Xor B])(a: A): F[B]
  }
  ```

  but should the order of arguments be switched in order to help Scala's type inference?
  (`scalaz` kept the argument order as it appears in the paper.)

**Comment by ceedubs** [comment]
@TomasMikula my 2 cents:

1) I'd be inclined to add `MonadRec`. In the very little I've played around to this, I found it annoying to have `Applicative` and `BindRec` littered all over the implicit params.
2) Yes, I like your idea to switch the params order.

**Comment by ceedubs** [comment]
Added in #1041.

**Comment by adelbertc** [comment]
@paf31 I wonder if there is such a thing/need for something like `ApplicativeRec` or `ApplyRec`? In exploring the MTL/tagless final stack safety question which `Free` gets.. for free, I figure this is where `MonadRec` comes into play... e.g. instead of

```haskell
class Monad m => MonadHttp m ...
```

you would have

```haskell
class MonadRec m => MonadHttp m ...
```

But there's also `FreeApplicative`.. so what of that?

**Comment by paf31** [comment]
Is there a good definition of "applicative tail recursion"?

**Comment by adelbertc** [comment]
I suppose I'm looking for something where

```scala
def blowStack[F[_]: Applicative, A](as: List[F[A]]): F[A] =
  as.foldRight(().pure[F])(_ *> _)
```

doesn't block stack (when "run")
