### ISSUE TITLE
Can't use eq if order is also imported

### ISSUE THREAD

**Issue by joprice** [typelevel/cats#811]
Is this expected?

``` scala
import cats._
import cats.std.all._
import cats.syntax.eq._
import cats.syntax.order._

class Test {
  1 === 2
}

// [error] ... value === is not a member of Int
// [error]   1 === 2
```

**Comment by joprice** [comment]
Ok this makes sense, since `OrderSyntax` extends `PartialOrderSyntax` extends `EqSyntax`.

**Comment by ceedubs** [comment]
I don't know of any way that we can work around this within cats, but I think that we should be sure to address the conflicting import problem in any import guide that may be created as part of #1026.

**Comment by diesalbla** [comment]
@kailuowang It has been three years since this issue was opened. Looking at it for a minute, I can see only two ways forward: 

The long way, and maybe right way, is to modify the traits `OrderSyntax` and `PartialOrderSyntax`, so that they no longer inherit from `EqSyntax` or each other. Each one would only provide the specific methods and operators introduced by their respective type-class, and not those from the other ones. This is similar to how `import cats.syntax.applicative._` does not bring `.map` or `.void`, and one has to use `cats.syntax.functor._`. This way would be both binary and source-breaking.

The other way is to leave it as is, and close this issue.

**Comment by kailuowang** [comment]
The fix requires breaking changes. I would vote for closing this issue. @lukajcb what do you think?

**Comment by tpolecat** [comment]
Agree re: closing

**Comment by diesalbla** [comment]
Are there any plans for a `cats 2.0` release, at some point, one in which breaking changes such as this one could be added?

**Comment by kailuowang** [comment]
The roadmap for 2019 is here https://github.com/typelevel/cats/blob/master/ROADMAP_2019.md
For breaking changes like the fix you suggested we'll have to wait for 3.0, which is likely to be post 2020.  It's not ideal to have inconsistencies, but we have to evaluate the benefit of fixing it against the cost of the breaking change for users.

**Comment by kailuowang** [comment]
sorry accidentally closed it, I meant to wait on hearing luka.

**Comment by LukaJCB** [comment]
I also agree to closing this issue, we can discuss refinement of the roadmap in the appropriate issue :)
