### ISSUE TITLE
we need to make a plan for automating the publishing of the documentation website

### ISSUE THREAD

**Issue by stew** [typelevel/cats#913]
as brought up by @longcao we need to

[ ] automate the publishing of the documentation website with the build
[ ] publish multiple versions of the website

**Comment by InTheNow** [comment]
see also https://github.com/typelevel/cats/issues/155 , https://github.com/typelevel/cats/pull/488 and https://github.com/typelevel/cats/pull/491

**Comment by InTheNow** [comment]
and https://github.com/typelevel/cats/issues/489

**Comment by stew** [comment]
ok, great, looks like this is already covered, I'm not surprised, but since this came up during the typelevel summit, I wanted to make sure it was captured. Looks like snice we have good coverage on this, I'll close this one

**Comment by stew** [comment]
oh, however all those are closed. I'm reopening :)

**Comment by InTheNow** [comment]
@stew, yep, those links were for reference only and this is definitely unfinished, so is an open issue.

As a side note, there may also have been some discussion on documentation tools in general ( always have a TOC, use tool X instead of Y, align tools with org Z, etc); if so, this issue should most definitely be part of of that larger epic, IMHO of course.

[ Hmm, I originally had a typo ^^ "As a snide note,....". What a difference that 'n' would have made ;) )

**Comment by armanbilge** [comment]
Fixed as of https://github.com/typelevel/cats/pull/4160.
