### ISSUE TITLE
OptionT.toRight/Left versus Xor.fromOption

### ISSUE THREAD

**Issue by lunaryorn** [typelevel/cats#930]
Hello,

I wonder how the cats API for OptionT and XorT came to be :relaxed:  Why is it `Xor.fromOption(...)`, but `OptionT.toRight`?

**Comment by ceedubs** [comment]
@lunaryorn I think it's probably because `OptionT` is housed in Cats, where it's convenient to add a `toRight` method to it, but `Option` is in the standard library. If you've imported `cats.implicits._`, then you should be able to call `toRightXor` on an `Option`. We couldn't call it `toRight` because there's already a `toRight` on `Option` that converts it to a `scala.util.Right`.

Does that clear it up a bit? Any suggestions for improvement?

**Comment by lunaryorn** [comment]
@ceedubs Maybe we could rename `.toRight` to `.toRightXorT` as well, then?  Not sure, but I somehow find `.toRight` a bit confusing, particularly since it's not actually sure that a `Right` value comes back…

**Comment by ceedubs** [comment]
@lunaryorn I guess `toRight` is a kind of confusing name for a method that doesn't necessarily return a `Right`. I guess it made sense to me early on because I saw both `toRight` and `toLeft` together, and I think seeing the two makes their intention a bit more clear. I'm open to ideas of clearer names that we could use.

It seems to me that `toRightXorT` doesn't really solve this problem though. It just kind of tacks on the information that's already in the return type in almost Hungarian notation. Since `toRight` is already taken on `Option`, and we have to use `toRightXor` there, I could see `toRightXorT` being adopted simply from a consistency argument though.

**Comment by lunaryorn** [comment]
@ceedubs I'm not really convinced of my proposal either, but I'm not that much against putting return types into methods.  I think these methods are mostly used in monadic `for` comprehensions with little to no type annotations; having information about the type in the method name helps to read such expressions without bothering the IDE's type at point functionality.

By the way, please excuse my delayed replies.

**Comment by lunaryorn** [comment]
@ceedubs I'm closing this issue.  My question is answered :)  Thanks for your help.
