### ISSUE TITLE
Typeclass implementation in scato

### ISSUE THREAD

**Issue by julien-truffaut** [typelevel/cats#963]
What do you think of the proposed implementation of typeclasses in scato ([see](https://github.com/jbgi/scato/raw/master/TypeClassesInScato.pdf)) ?

It seems to remove the need of complex instance hierarchy definition and it is convenient for default implementation.

**Comment by refried** [comment]
I think I like it.

**Comment by adelbertc** [comment]
One thing this solves (I think) that I like is making it easier to program in an "MTL" style, e.g. currently,

```scala
trait MonadFoo[M[_]] extends Monad[M] {
  def foo: M[Int]
}
```

to define a `MonadFoo` for some type we need to also implement `Monad` which may well already be defined in Cats (or somewhere else) which is now duplicating work and morally required another round of law-checking.

**Comment by mpilquist** [comment]
Seems like this would drastically impact cats-kernel and cats-core, impacting users quite a bit. I think I'd rather see how Scato plays out in other libraries before adopting this style.

**Comment by non** [comment]
I concur with @mpilquist. It's an interesting idea (separating out the OO encoding from the type class itself) and it seems like the encoding could be compatible with a Simulacrum-like approach. But I think it would be pretty disruptive at this point to consider changing all our encodings.

The flip side to this is that if you do think it is worth it to delay cats 1.0 so we can experiment with this encoding (since after 1.0 our source and binary compatibility requirements will be in effect), please speak up ASAP. 😉

**Comment by ceedubs** [comment]
I'm definitely intrigued by this approach. My inclination would be to not delay cats 1.0 for it, but if someone was feeling very ambitious and submitted a PR this week or something, I would certainly give it careful consideration.

Some questions that come to mind for me are:
- It looks like it could result in slightly more overhead in certain situations, but how significant would it be?
- Would this reduce (or remove) the need for prioritized instance hierarchies?
